import 'server-only';
import { inTransaction, query } from '@/lib/db/pool';
import { normalizarRutDb, validarRutM11 } from '@/lib/reglas/reserva';
import { obtenerReglasReserva } from '@/lib/db/reservas';
import { cancelacionDirectaHabilitada } from '@/lib/reglas/reserva';

export async function listarMisReservas(rutInput:string){ if(!validarRutM11(rutInput)) throw new Error('RUT inválido.'); const rut=normalizarRutDb(rutInput); const [cab,lineas]=await Promise.all([query<any>(`SELECT referencia_reserva,COALESCE(MAX(NULLIF(codigo_reserva,'')),referencia_reserva) codigo_reserva,MIN(fecha) desde,MAX(fecha) hasta,COUNT(*) FILTER (WHERE COALESCE(estado_reserva,'ACTIVA')='ACTIVA') servicios_activos,STRING_AGG(DISTINCT COALESCE(NULLIF(estado_pago,''),'Pendiente'), ', ') estado_pago,STRING_AGG(DISTINCT COALESCE(NULLIF(estado_reserva,''),'ACTIVA'), ', ') estado_reserva FROM solicitudes WHERE rut=$1 AND COALESCE(NULLIF(referencia_reserva,''),'')<>'' GROUP BY referencia_reserva ORDER BY MAX(fecha) DESC`,[rut]),query<any>(`SELECT id,referencia_reserva,fecha,servicio,plato_reservado,estado_reserva,COALESCE(NULLIF(estado_pago,''),'Pendiente') estado_pago FROM solicitudes WHERE rut=$1 ORDER BY fecha DESC,servicio,id`,[rut])]); return {rut,cab,lineas}; }
export async function cancelarServicio(rutInput:string,id:number){ if(!validarRutM11(rutInput)) throw new Error('RUT inválido.'); const rut=normalizarRutDb(rutInput); const rows=await query<any>(`SELECT id,fecha,servicio,referencia_reserva,COALESCE(estado_reserva,'ACTIVA') estado_reserva FROM solicitudes WHERE id=$1 AND rut=$2 LIMIT 1`,[id,rut]); const r=rows[0]; if(!r||r.estado_reserva!=='ACTIVA') throw new Error('Servicio no disponible para cancelar.'); const reglas=await obtenerReglasReserva(); if(!cancelacionDirectaHabilitada(String(r.fecha),String(r.servicio),Number(reglas.cancelacion_directa_horas))) throw new Error('El servicio está fuera de la ventana de cancelación directa.'); await inTransaction(async c=>{await c.query(`UPDATE solicitudes SET estado_reserva='CANCELADA',fecha_modificacion=$1,modificado_por=$2 WHERE id=$3 AND rut=$2 AND COALESCE(estado_reserva,'ACTIVA')='ACTIVA'`,[new Date().toISOString(),rut,id]); await c.query(`INSERT INTO auditoria_acciones (fecha,usuario,accion,tabla,registro_id,valor_anterior,valor_nuevo,detalle) VALUES ($1,$2,'CANCELAR_SERVICIOS','solicitudes',$3,'ACTIVA','CANCELADA','Cancelación dentro de ventana')`,[new Date().toISOString(),rut,String(id)]);}); }
export async function guardarReclamo(rutInput:string,tipo:string,categoria:string,mensaje:string){ if(!validarRutM11(rutInput)) throw new Error('RUT inválido.'); if(!mensaje.trim()) throw new Error('Escribe un mensaje.'); const rut=normalizarRutDb(rutInput); const c=(await query<any>(`SELECT nombre FROM comensales WHERE rut=$1`,[rut]))[0]; if(!c) throw new Error('Comensal no encontrado.'); await query(`INSERT INTO reclamos_sugerencias (rut,nombre,tipo,categoria,mensaje,fecha,estado) VALUES ($1,$2,$3,$4,$5,$6,'Pendiente')`,[rut,c.nombre,tipo,categoria,mensaje.trim(),new Date().toISOString()]); }
