import 'server-only';
import { inTransaction, query } from '@/lib/db/pool';

export async function ensureCoordSchema(){
  await inTransaction(async c=>{
    await c.query(`CREATE TABLE IF NOT EXISTS minuta_revision_coordinacion (id SERIAL PRIMARY KEY,fecha TEXT NOT NULL,servicio TEXT NOT NULL,tipo_opcion TEXT NOT NULL,plato_actual TEXT,accion TEXT NOT NULL,observacion TEXT,plato_propuesto TEXT,usuario TEXT,fecha_accion TEXT,estado TEXT DEFAULT 'Pendiente')`);
    await c.query(`ALTER TABLE minuta_revision_coordinacion ADD COLUMN IF NOT EXISTS flujo_id INTEGER`);
    await c.query(`ALTER TABLE minuta_revision_coordinacion ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 1`);
    await c.query(`CREATE TABLE IF NOT EXISTS minuta_flujo_coordinacion (id SERIAL PRIMARY KEY,fecha_desde TEXT NOT NULL,fecha_hasta TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,estado TEXT NOT NULL DEFAULT 'EN_REVISION',observacion TEXT,enviado_por TEXT,enviado_at TEXT,coordinador TEXT,coordinacion_at TEXT,activo INTEGER DEFAULT 1)`);
  });
}
export async function flujosPendientes(){ await ensureCoordSchema(); return query<any>(`SELECT id,fecha_desde,fecha_hasta,version,estado,observacion,enviado_por,enviado_at FROM minuta_flujo_coordinacion WHERE COALESCE(activo,1)=1 AND estado='EN_REVISION' ORDER BY enviado_at DESC,id DESC`); }
export async function resumenFlujos(){ await ensureCoordSchema(); return query<any>(`SELECT estado,COUNT(*) cantidad FROM minuta_flujo_coordinacion WHERE COALESCE(activo,1)=1 GROUP BY estado ORDER BY estado`); }
export async function minutaFlujo(flujoId:number){ await ensureCoordSchema(); const f=(await query<any>(`SELECT * FROM minuta_flujo_coordinacion WHERE id=$1 LIMIT 1`,[flujoId]))[0]; if(!f) return {flujo:null,minuta:[],revisiones:[]}; const [minuta,revisiones]=await Promise.all([query<any>(`SELECT id,fecha,servicio,tipo_opcion,plato FROM minutas WHERE COALESCE(activo,1)=1 AND fecha BETWEEN $1 AND $2 ORDER BY fecha,CASE servicio WHEN 'Desayuno' THEN 1 WHEN 'Almuerzo' THEN 2 WHEN 'Once' THEN 3 WHEN 'Cena' THEN 4 ELSE 5 END,tipo_opcion,plato`,[f.fecha_desde,f.fecha_hasta]),query<any>(`SELECT fecha,servicio,tipo_opcion,plato_actual,accion,observacion FROM minuta_revision_coordinacion WHERE flujo_id=$1 AND version=$2 ORDER BY fecha,id`,[flujoId,f.version])]); return {flujo:f,minuta,revisiones}; }
export async function guardarDia(flujoId:number,fecha:string,decisiones:Array<{servicio:string;tipo_opcion:string;plato:string;accion:'SIN_OBSERVACION'|'CON_OBSERVACION';observacion:string}>,usuario:string){ await ensureCoordSchema(); const f=(await query<any>(`SELECT version,estado FROM minuta_flujo_coordinacion WHERE id=$1`,[flujoId]))[0]; if(!f||f.estado!=='EN_REVISION') throw new Error('La revisión ya no está disponible.'); for(const d of decisiones){ if(d.accion==='CON_OBSERVACION'&&!d.observacion.trim()) throw new Error(`Falta comentario en ${d.servicio} · ${d.tipo_opcion}`); }
  await inTransaction(async c=>{ await c.query(`DELETE FROM minuta_revision_coordinacion WHERE flujo_id=$1 AND version=$2 AND fecha=$3`,[flujoId,f.version,fecha]); for(const d of decisiones){ await c.query(`INSERT INTO minuta_revision_coordinacion (flujo_id,version,fecha,servicio,tipo_opcion,plato_actual,accion,observacion,plato_propuesto,usuario,fecha_accion,estado) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,NULL,$9,$10,'GUARDADA')`,[flujoId,f.version,fecha,d.servicio,d.tipo_opcion,d.plato,d.accion,d.observacion,usuario,new Date().toISOString()]); } await c.query(`INSERT INTO auditoria_acciones (fecha,usuario,accion,tabla,registro_id,valor_anterior,valor_nuevo,detalle) VALUES ($1,$2,'GUARDAR_REVISION_DIARIA','minuta_revision_coordinacion',$3,'','GUARDADA',$4)`,[new Date().toISOString(),usuario,`${flujoId}:${fecha}`,`${decisiones.length} ítems revisados`]); }); }
export async function finalizarRevision(flujoId:number,usuario:string){ const data=await minutaFlujo(flujoId); if(!data.flujo) throw new Error('Flujo no encontrado.'); const fechas=[...new Set(data.minuta.map((x:any)=>String(x.fecha)))]; for(const fecha of fechas){ const total=data.minuta.filter((x:any)=>String(x.fecha)===fecha).length; const rev=data.revisiones.filter((x:any)=>String(x.fecha)===fecha).length; if(rev<total) throw new Error('Debes revisar todos los días antes de finalizar.'); }
  const obs=data.revisiones.filter((x:any)=>x.accion==='CON_OBSERVACION'); const nuevo=obs.length?'OBSERVADA':'AUTORIZADA'; const texto=obs.map((r:any)=>`${r.fecha} · ${r.servicio} · ${r.tipo_opcion}: ${r.observacion}`).join('\n'); await inTransaction(async c=>{ await c.query(`UPDATE minuta_flujo_coordinacion SET estado=$1,observacion=$2,coordinador=$3,coordinacion_at=$4 WHERE id=$5 AND estado='EN_REVISION'`,[nuevo,texto,usuario,new Date().toISOString(),flujoId]); await c.query(`INSERT INTO auditoria_acciones (fecha,usuario,accion,tabla,registro_id,valor_anterior,valor_nuevo,detalle) VALUES ($1,$2,'FINALIZAR_REVISION_COORDINADOR','minuta_flujo_coordinacion',$3,'EN_REVISION',$4,$5)`,[new Date().toISOString(),usuario,String(flujoId),nuevo,`${obs.length} observación(es)`]); }); return nuevo; }
