import 'server-only';
import { escCorreo } from '@/lib/email/standard-layout';

export function correoHtmlAlemzinChefPrueba(title:string,content:string,eyebrow='CASINO MAMUIL'){
  const personaje=String(process.env.ALEMZIN_CHEF_EMAIL_IMAGE_URL||'').trim();
  const personajeCelda=personaje
    ? `<td width="116" align="center" valign="bottom" style="padding:14px 18px 0 4px"><img src="${escCorreo(personaje)}" alt="Alemzín Chef" width="92" style="display:block;width:92px;max-width:92px;height:auto;border:0"/></td>`
    : `<td width="116" align="center" valign="middle" style="padding:14px 18px 14px 4px"><div style="width:88px;height:88px;border:2px dashed #7FE1D6;border-radius:14px;color:#D8FAF6;font-size:11px;line-height:1.25;padding:9px;box-sizing:border-box;text-align:center"><b>ALEMZÍN CHEF</b><br><span style="font-size:10px">activo gráfico pendiente</span></div></td>`;
  return `<!doctype html><html><body style="margin:0;background:#f4f6f5;font-family:Arial,Helvetica,sans-serif;color:#14232d"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4f6f5;padding:24px 10px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;background:#fff;border:1px solid #d7e1dc;border-radius:14px;overflow:hidden"><tr><td style="background:#0B2D5B;padding:0"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:22px 10px 22px 24px;color:white"><div style="font-size:21px;font-weight:800;letter-spacing:.5px">ALEMSI · ${escCorreo(eyebrow)}</div><div style="margin-top:5px;color:#7FE1D6;font-size:12px;font-weight:800">SERVICIO DE ALIMENTACIÓN</div><div style="margin-top:10px;font-size:11px;line-height:1.35;color:#dbe8ef">Propuesta paralela de identidad para correos. El personaje no sustituye el contenido operativo.</div></td>${personajeCelda}</tr></table></td></tr><tr><td style="padding:24px"><div style="font-size:22px;font-weight:800;color:#0B2D5B;margin-bottom:18px">${escCorreo(title)}</div>${content}</td></tr><tr><td style="border-top:1px solid #d7e1dc;padding:14px 24px;font-size:11px;color:#6b7570">ALEMSI · Casino Mamuil · Alimentamos bien, cuidamos a las personas.</td></tr></table></td></tr></table></body></html>`;
}
