import 'server-only';
import { enviarCorreoSmtp, type SmtpDelivery } from '@/lib/email/smtp';

type Choice={fecha:string;servicio:string;plato:string;tipo_opcion?:string};
function enlaceComprobante(origin:string,token:string){const base=new URL(origin);base.pathname=`/comprobante/${encodeURIComponent(token)}`;base.search='';base.hash='';return base.toString();}
function esc(v:unknown){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));}
function money(v:number){return new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(v||0));}
function dateCL(v:string){const [y,m,d]=String(v).split('-');return y&&m&&d?`${d}-${m}-${y}`:v;}
function transferRows(){const rows=[['Banco',process.env.TRANSFER_BANK],['Tipo de cuenta',process.env.TRANSFER_ACCOUNT_TYPE],['N° de cuenta',process.env.TRANSFER_ACCOUNT_NUMBER],['Titular',process.env.TRANSFER_HOLDER],['RUT',process.env.TRANSFER_RUT],['Correo transferencia',process.env.TRANSFER_EMAIL]].filter(([,v])=>String(v||'').trim());return rows.map(([k,v])=>`<tr><td style="padding:6px 8px;color:#5b6670;width:38%">${esc(k)}</td><td style="padding:6px 8px;font-weight:700;color:#0B2D5B">${esc(v)}</td></tr>`).join('');}
function layout(title:string,content:string){const banner=String(process.env.SEPTEMBER_EMAIL_BANNER_URL||'').trim();return `<!doctype html><html><body style="margin:0;background:#f4f6f5;font-family:Arial,Helvetica,sans-serif;color:#14232d"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4f6f5;padding:24px 10px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;background:#fff;border:1px solid #d7e1dc;border-radius:12px;overflow:hidden">${banner?`<tr><td style="padding:0"><img src="${esc(banner)}" alt="ALEMSI Casino · Septiembre · Fiestas Patrias" width="680" style="display:block;width:100%;max-width:680px;height:auto;border:0"/></td></tr>`:`<tr><td style="background:#0B2D5B;padding:20px 24px;color:white"><div style="font-size:20px;font-weight:800;letter-spacing:.5px">ALEMSI · CASINO MAMUIL</div><div style="margin-top:4px;color:#7FE1D6;font-size:12px;font-weight:700">SEPTIEMBRE · FIESTAS PATRIAS</div></td></tr>`}<tr><td style="padding:24px"><div style="font-size:22px;font-weight:800;color:#0B2D5B;margin-bottom:8px">${esc(title)}</div><div style="font-size:14px;font-weight:800;color:#087A46;margin-bottom:18px">¡Feliz Mes de la Patria! ALEMSI te desea unas felices Fiestas Patrias.</div>${content}</td></tr><tr><td style="border-top:1px solid #d7e1dc;padding:14px 24px;font-size:11px;color:#6b7570">ALEMSI · Casino Mamuil · Alimentamos bien, cuidamos a las personas.</td></tr></table></td></tr></table></body></html>`;}

export function correoReservaConfirmada(input:{correo:string;codigo:string;referencia:string;pagoToken?:string;origin:string;rut?:string;total?:number;method?:string;choices?:Choice[]}){
 const choices=input.choices||[]; const link=input.pagoToken?enlaceComprobante(input.origin,input.pagoToken):'';
 const rows=choices.map(c=>`<tr><td style="padding:7px;border-bottom:1px solid #e5ece8">${esc(dateCL(c.fecha))}</td><td style="padding:7px;border-bottom:1px solid #e5ece8">${esc(c.servicio)}</td><td style="padding:7px;border-bottom:1px solid #e5ece8"><b>${esc(c.plato)}</b>${c.tipo_opcion?`<div style="font-size:11px;color:#6b7570">${esc(c.tipo_opcion)}</div>`:''}</td></tr>`).join('');
 const transfer=/transfer/i.test(String(input.method||'')); const bank=transferRows();
 const html=layout('Reserva confirmada',`<p style="margin:0 0 16px;font-size:14px;line-height:1.5;color:#42515a">Tu reserva fue registrada correctamente.</p><table role="presentation" width="100%" style="border-collapse:collapse;background:#f7faf8;border:1px solid #d7e1dc"><tr><td style="padding:8px;color:#5b6670">Código de reserva</td><td style="padding:8px;font-weight:800;color:#0B2D5B">${esc(input.codigo)}</td></tr>${input.rut?`<tr><td style="padding:8px;color:#5b6670">RUT</td><td style="padding:8px;font-weight:700">${esc(input.rut)}</td></tr>`:''}<tr><td style="padding:8px;color:#5b6670">Método de pago</td><td style="padding:8px;font-weight:700">${esc(input.method||'Transferencia bancaria')}</td></tr><tr><td style="padding:8px;color:#5b6670">Deuda total pendiente</td><td style="padding:8px;font-size:20px;font-weight:800;color:#087A46">${money(Number(input.total||0))}</td></tr></table>${rows?`<div style="margin-top:20px;font-weight:800;color:#0B2D5B">Detalle reservado</div><table role="presentation" width="100%" style="margin-top:8px;border-collapse:collapse;border:1px solid #d7e1dc"><tr style="background:#0B3B78;color:white"><th align="left" style="padding:7px">Fecha</th><th align="left" style="padding:7px">Servicio</th><th align="left" style="padding:7px">Plato</th></tr>${rows}</table>`:''}${transfer?`<div style="margin-top:20px;font-weight:800;color:#0B2D5B">Datos para transferencia</div>${bank?`<table role="presentation" width="100%" style="margin-top:8px;border-collapse:collapse;background:#f7faf8;border:1px solid #d7e1dc">${bank}</table>`:`<div style="margin-top:8px;padding:12px;background:#fff8e8;border:1px solid #f0d89a;border-radius:8px;font-size:13px">Los datos bancarios deben estar configurados por Administración.</div>`}`:''}${link?`<div style="margin-top:22px;text-align:center"><a href="${esc(link)}" style="display:inline-block;background:#0D9B91;color:white;text-decoration:none;font-weight:800;padding:12px 18px;border-radius:8px">Subir comprobante de pago</a></div>`:''}<div style="margin-top:20px;padding:13px 15px;background:#eef7f6;border-left:4px solid #0D9B91;color:#24434a;font-size:13px;line-height:1.45"><b>Importante:</b> no es obligación realizar el pago antes del consumo. Puedes efectuar la transferencia y cargar tu comprobante conforme al procedimiento del Casino.</div>`);
 const text=[`Reserva confirmada ${input.codigo}`,input.rut?`RUT: ${input.rut}`:'',`Método: ${input.method||'Transferencia bancaria'}`,`Deuda total pendiente: ${money(Number(input.total||0))}`,...choices.map(c=>`${dateCL(c.fecha)} · ${c.servicio} · ${c.plato}`),'Importante: no es obligación realizar el pago antes del consumo.','¡Feliz Mes de la Patria! ALEMSI te desea unas felices Fiestas Patrias.',link?`Comprobante: ${link}`:''].filter(Boolean).join('\n');
 return{to:input.correo,subject:`Reserva confirmada ${input.codigo} · ALEMSI`,text,html};
}
export function notificarReservaConfirmada(input:Parameters<typeof correoReservaConfirmada>[0]):Promise<SmtpDelivery>{return enviarCorreoSmtp(correoReservaConfirmada(input));}
export function notificarComprobanteRecibido(input:{correo:string;referencia:string;pagoToken:string;origin:string}):Promise<SmtpDelivery>{const link=enlaceComprobante(input.origin,input.pagoToken);return enviarCorreoSmtp({to:input.correo,subject:'Comprobante recibido · ALEMSI',text:`Recibimos correctamente tu comprobante.\n${link}`,html:layout('Comprobante recibido',`<p style="font-size:15px;line-height:1.5">Recibimos correctamente tu comprobante de pago.</p><div style="margin-top:20px;text-align:center"><a href="${esc(link)}" style="display:inline-block;background:#0D9B91;color:white;text-decoration:none;font-weight:800;padding:12px 18px;border-radius:8px">Consultar comprobante</a></div>`)})}
