import 'server-only';
import { enviarCorreoSmtp, type SmtpDelivery } from '@/lib/email/smtp';
import { generarReservaPdf } from '@/lib/email/reserva-pdf';

type Choice={fecha:string;servicio:string;plato:string;tipo_opcion?:string};
function enlaceComprobante(origin:string,token:string){const base=new URL(origin);base.pathname=`/comprobante/${encodeURIComponent(token)}`;base.search='';base.hash='';return base.toString();}
function enlaceReserva(origin:string){const base=new URL(origin);base.pathname='/reserva';base.search='';base.hash='';return base.toString();}
function esc(v:unknown){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));}
function money(v:number){return new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(v||0));}
function transferRows(){const rows=[['Banco',process.env.TRANSFER_BANK],['Tipo de cuenta',process.env.TRANSFER_ACCOUNT_TYPE],['N° de cuenta',process.env.TRANSFER_ACCOUNT_NUMBER],['Titular',process.env.TRANSFER_HOLDER],['RUT',process.env.TRANSFER_RUT],['Correo transferencia',process.env.TRANSFER_EMAIL]].filter(([,v])=>String(v||'').trim());return rows.map(([k,v])=>`<tr><td style="padding:6px 8px;color:#5b6670;width:38%">${esc(k)}</td><td style="padding:6px 8px;font-weight:700;color:#0B2D5B">${esc(v)}</td></tr>`).join('');}
function layout(title:string,content:string){const banner=String(process.env.SEPTEMBER_EMAIL_BANNER_URL||'').trim();return `<!doctype html><html><body style="margin:0;background:#f4f6f5;font-family:Arial,Helvetica,sans-serif;color:#14232d"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4f6f5;padding:24px 10px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;background:#fff;border:1px solid #d7e1dc;border-radius:12px;overflow:hidden">${banner?`<tr><td style="padding:0"><img src="${esc(banner)}" alt="ALEMSI Casino · Septiembre · Fiestas Patrias" width="680" style="display:block;width:100%;max-width:680px;height:auto;border:0"/></td></tr>`:`<tr><td style="background:#0B2D5B;padding:20px 24px;color:white"><div style="font-size:20px;font-weight:800;letter-spacing:.5px">ALEMSI · CASINO MAMUIL</div><div style="margin-top:4px;color:#7FE1D6;font-size:12px;font-weight:700">SEPTIEMBRE · FIESTAS PATRIAS</div></td></tr>`}<tr><td style="padding:24px"><div style="font-size:22px;font-weight:800;color:#0B2D5B;margin-bottom:8px">${esc(title)}</div><div style="font-size:14px;font-weight:800;color:#087A46;margin-bottom:18px">¡Feliz Mes de la Patria! ALEMSI te desea unas felices Fiestas Patrias.</div>${content}</td></tr><tr><td style="border-top:1px solid #d7e1dc;padding:14px 24px;font-size:11px;color:#6b7570">ALEMSI · Casino Mamuil · Alimentamos bien, cuidamos a las personas.</td></tr></table></td></tr></table></body></html>`;}

export type ReservaMailInput={correo:string;codigo:string;referencia:string;pagoToken?:string;origin:string;rut?:string;total?:number;method?:string;choices?:Choice[]};
export function correoReservaConfirmada(input:ReservaMailInput){
 const link=input.pagoToken?enlaceComprobante(input.origin,input.pagoToken):'';
 const transfer=/transfer/i.test(String(input.method||'')); const bank=transferRows();
 const html=layout('Reserva confirmada',`<p style="margin:0 0 16px;font-size:14px;line-height:1.5;color:#42515a">Tu reserva fue registrada correctamente.</p><table role="presentation" width="100%" style="border-collapse:collapse;background:#f7faf8;border:1px solid #d7e1dc"><tr><td style="padding:8px;color:#5b6670">Código de reserva</td><td style="padding:8px;font-weight:800;color:#0B2D5B">${esc(input.codigo)}</td></tr>${input.rut?`<tr><td style="padding:8px;color:#5b6670">RUT</td><td style="padding:8px;font-weight:700">${esc(input.rut)}</td></tr>`:''}<tr><td style="padding:8px;color:#5b6670">Método de pago</td><td style="padding:8px;font-weight:700">${esc(input.method||'Transferencia bancaria')}</td></tr><tr><td style="padding:8px;color:#5b6670">Deuda total pendiente</td><td style="padding:8px;font-size:20px;font-weight:800;color:#087A46">${money(Number(input.total||0))}</td></tr></table><div style="margin-top:18px;padding:14px 16px;background:#eef7f6;border:1px solid #cfe5df;border-radius:8px;color:#24434a;font-size:14px;line-height:1.5"><b>Detalle de tu reserva:</b> se adjunta a este correo un PDF con el detalle completo de las fechas, servicios, opciones y platos reservados.</div>${transfer?`<div style="margin-top:20px;font-weight:800;color:#0B2D5B">Datos para transferencia</div>${bank?`<table role="presentation" width="100%" style="margin-top:8px;border-collapse:collapse;background:#f7faf8;border:1px solid #d7e1dc">${bank}</table>`:`<div style="margin-top:8px;padding:12px;background:#fff8e8;border:1px solid #f0d89a;border-radius:8px;font-size:13px">Los datos bancarios deben estar configurados por Administración.</div>`}`:''}${link?`<div style="margin-top:22px;text-align:center"><a href="${esc(link)}" style="display:inline-block;background:#0D9B91;color:white;text-decoration:none;font-weight:800;padding:12px 18px;border-radius:8px">Subir comprobante de pago</a></div>`:''}<div style="margin-top:20px;padding:13px 15px;background:#eef7f6;border-left:4px solid #0D9B91;color:#24434a;font-size:13px;line-height:1.45"><b>Importante:</b> no es obligación realizar el pago antes del consumo. Puedes efectuar la transferencia y cargar tu comprobante conforme al procedimiento del Casino.</div>`);
 const text=[`Reserva confirmada ${input.codigo}`,input.rut?`RUT: ${input.rut}`:'',`Método: ${input.method||'Transferencia bancaria'}`,`Deuda total pendiente: ${money(Number(input.total||0))}`,'Se adjunta a este correo el detalle completo de su reserva en PDF.','Importante: no es obligación realizar el pago antes del consumo.','¡Feliz Mes de la Patria! ALEMSI te desea unas felices Fiestas Patrias.',link?`Subir comprobante: ${link}`:''].filter(Boolean).join('\n');
 return{to:input.correo,subject:`Reserva confirmada ${input.codigo} · ALEMSI`,text,html};
}
export async function notificarReservaConfirmada(input:ReservaMailInput):Promise<SmtpDelivery>{const base=correoReservaConfirmada(input);const pdf=await generarReservaPdf({codigo:input.codigo,rut:input.rut,total:input.total,choices:input.choices});return enviarCorreoSmtp({...base,attachments:[{filename:`Reserva-${input.codigo}.pdf`,contentType:'application/pdf',content:pdf}]});}

export function notificarPagoAprobado(input:{correo:string;codigo:string;total:number;origin:string;manual?:boolean}):Promise<SmtpDelivery>{
 const link=enlaceReserva(input.origin);
 const tipo=input.manual?'validado manualmente por Finanzas':'validado correctamente por Finanzas';
 const html=layout('Pago confirmado',`<p style="margin:0 0 16px;font-size:15px;line-height:1.55;color:#42515a">Tu pago fue ${esc(tipo)}. Tu situación financiera se encuentra regularizada.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:separate;border-spacing:8px 0;margin:0 -8px;width:calc(100% + 16px)"><tr><td width="50%" style="padding:14px;vertical-align:top;background:#eef7f6;border:1px solid #cfe5df;border-radius:8px"><div style="font-size:11px;color:#5b6670;text-transform:uppercase">Estado</div><div style="margin-top:4px;font-size:16px;font-weight:800;color:#087A46">Pago validado</div></td><td width="50%" style="padding:14px;vertical-align:top;background:#eef7f6;border:1px solid #cfe5df;border-radius:8px"><div style="font-size:11px;color:#5b6670;text-transform:uppercase">Monto validado</div><div style="margin-top:4px;font-size:16px;font-weight:800;color:#087A46">${money(input.total)}</div></td></tr></table><div style="margin-top:18px;padding:14px 16px;background:#f7faf8;border:1px solid #d7e1dc;border-radius:8px;font-size:14px;line-height:1.5"><b>Reserva habilitada</b><br>Puedes volver a realizar nuevas reservas conforme a las reglas vigentes del Casino.</div><div style="margin-top:22px;text-align:center"><a href="${esc(link)}" style="display:inline-block;background:#0D9B91;color:white;text-decoration:none;font-weight:800;padding:12px 18px;border-radius:8px">Volver a reservar</a></div><div style="margin-top:20px;padding-top:12px;border-top:1px solid #d7e1dc;font-size:12px;color:#5b6670">Código de reserva: <b style="color:#0B2D5B">${esc(input.codigo)}</b></div>`);
 const text=[`Pago confirmado · ${input.codigo}`,`Monto validado: ${money(input.total)}`,'Estado: PAGO VALIDADO','Tu situación se encuentra regularizada y puedes volver a realizar nuevas reservas.',`Volver a reservar: ${link}`].join('\n');
 return enviarCorreoSmtp({to:input.correo,subject:`Pago confirmado ${input.codigo} · ALEMSI`,text,html});
}

export function notificarComprobanteRechazado(input:{correo:string;codigo:string;total:number;motivo:string;pagoToken?:string;origin:string}):Promise<SmtpDelivery>{const link=input.pagoToken?enlaceComprobante(input.origin,input.pagoToken):'';const html=layout('Comprobante rechazado',`<div style="margin-bottom:18px;padding:15px 16px;background:#fff3f3;border-left:4px solid #9B2C2C;font-size:15px;line-height:1.5;color:#542020"><b>No fue posible validar el comprobante.</b><br>El monto continúa pendiente.</div><div style="padding:14px;background:#f7faf8;border:1px solid #d7e1dc;border-radius:8px"><div style="font-size:11px;color:#5b6670;text-transform:uppercase">Monto pendiente</div><div style="margin-top:4px;font-size:17px;font-weight:800;color:#9B2C2C">${money(input.total)}</div></div><div style="margin-top:18px;font-size:16px;font-weight:800;color:#0B2D5B">Motivo informado por Finanzas</div><div style="margin-top:8px;padding:15px 16px;background:#fff8e8;border:1px solid #f0d89a;border-radius:8px;font-size:15px;line-height:1.55">${esc(input.motivo)}</div>${link?`<div style="margin-top:22px;text-align:center"><a href="${esc(link)}" style="display:inline-block;background:#0D9B91;color:white;text-decoration:none;font-weight:800;padding:12px 18px;border-radius:8px">Cargar nuevo comprobante</a></div>`:''}<p style="margin:18px 0 0;font-size:13px;line-height:1.5;color:#42515a">La reserva permanecerá pendiente hasta que Finanzas pueda validar el pago. El comprobante rechazado se conserva en el historial.</p><div style="margin-top:18px;padding-top:12px;border-top:1px solid #d7e1dc;font-size:12px;color:#5b6670">Código de reserva: <b style="color:#0B2D5B">${esc(input.codigo)}</b></div>`);const text=[`Comprobante rechazado · ${input.codigo}`,`Monto pendiente: ${money(input.total)}`,`Motivo: ${input.motivo}`,link?`Cargar nuevo comprobante: ${link}`:'','La reserva permanece pendiente hasta que Finanzas valide el pago.'].filter(Boolean).join('\n');return enviarCorreoSmtp({to:input.correo,subject:`Comprobante rechazado ${input.codigo} · ALEMSI`,text,html});}
export function notificarSolicitudInformacionPago(input:{correo:string;codigo:string;total:number;pagoToken?:string;origin:string}):Promise<SmtpDelivery>{const link=input.pagoToken?enlaceComprobante(input.origin,input.pagoToken):'';const html=layout('Información de pago pendiente',`<div style="margin-bottom:18px;padding:15px 16px;background:#fff8e8;border-left:4px solid #D4AF37;font-size:15px;line-height:1.5;color:#493b16"><b>Finanzas necesita información para identificar el pago.</b><br>Mientras no exista validación, el saldo continúa pendiente.</div><div style="padding:14px;background:#f7faf8;border:1px solid #d7e1dc;border-radius:8px"><div style="font-size:11px;color:#5b6670;text-transform:uppercase">Monto pendiente</div><div style="margin-top:4px;font-size:17px;font-weight:800;color:#087A46">${money(input.total)}</div></div><div style="margin-top:18px;padding:15px 16px;background:#eef7f6;border:1px solid #cfe5df;border-radius:8px;font-size:14px;line-height:1.55"><b>¿Qué debes hacer?</b><br>Si ya realizaste el pago, carga el comprobante o respaldo correspondiente. Si pagaste por otro medio, informa los antecedentes que permitan asociarlo a tu reserva.</div>${link?`<div style="margin-top:22px;text-align:center"><a href="${esc(link)}" style="display:inline-block;background:#0D9B91;color:white;text-decoration:none;font-weight:800;padding:12px 18px;border-radius:8px">Informar o cargar comprobante</a></div>`:''}<div style="margin-top:18px;padding-top:12px;border-top:1px solid #d7e1dc;font-size:12px;color:#5b6670">Código de reserva: <b style="color:#0B2D5B">${esc(input.codigo)}</b></div>`);const text=[`Información de pago pendiente · ${input.codigo}`,`Monto pendiente: ${money(input.total)}`,'Finanzas aún no ha podido identificar información suficiente para asociar el pago a tu reserva.',link?`Informar o cargar comprobante: ${link}`:'','Mientras no exista validación de Finanzas, el saldo continúa pendiente.'].filter(Boolean).join('\n');return enviarCorreoSmtp({to:input.correo,subject:`Información de pago pendiente ${input.codigo} · ALEMSI`,text,html});}
export function notificarComprobanteRecibido(input:{correo:string;referencia:string;pagoToken:string;origin:string}):Promise<SmtpDelivery>{const link=enlaceComprobante(input.origin,input.pagoToken);return enviarCorreoSmtp({to:input.correo,subject:'Comprobante recibido · ALEMSI',text:`Recibimos correctamente tu comprobante.\n${link}`,html:layout('Comprobante recibido',`<p style="font-size:15px;line-height:1.5">Recibimos correctamente tu comprobante de pago.</p><div style="margin-top:20px;text-align:center"><a href="${esc(link)}" style="display:inline-block;background:#0D9B91;color:white;text-decoration:none;font-weight:800;padding:12px 18px;border-radius:8px">Consultar comprobante</a></div>`)})}
