import { NextRequest,NextResponse } from 'next/server';
import { PDFDocument,StandardFonts,rgb } from 'pdf-lib';
import { requireUser } from '@/lib/auth/session';
import { financeExportData } from '@/lib/finanzas/export';

function filters(req:NextRequest){const p=req.nextUrl.searchParams;return{desde:p.get('desde')||'',hasta:p.get('hasta')||'',institucion:p.get('institucion')||'',medio:p.get('medio')||'',q:p.get('q')||'',estado:p.get('estado')||'global'};}
const escXml=(v:unknown)=>String(v??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]||c));
const csvCell=(v:unknown)=>{const s=String(v??'');return /[;"\n\r]/.test(s)?`"${s.replace(/"/g,'""')}"`:s};
function csv(data:any){const cols=['codigo_reserva','rut','comensal','institucion','tipo_cliente','fecha','servicio','plato','opcion','valor_servicio','monto_reserva','medio_pago','estado_financiero','estado_comprobante','estado_visible','motivo'];return '\uFEFF'+[cols.join(';'),...data.detail.map((r:any)=>cols.map(c=>csvCell(r[c])).join(';'))].join('\r\n');}
function xml(data:any){const f=data.filters;return `<?xml version="1.0" encoding="UTF-8"?>\n<informe_financiero><filtros><desde>${escXml(f.desde)}</desde><hasta>${escXml(f.hasta)}</hasta><institucion>${escXml(f.institucion||'Todas')}</institucion><medio_pago>${escXml(f.medio||'Todos')}</medio_pago><estado>${escXml(f.estado)}</estado><busqueda>${escXml(f.q)}</busqueda></filtros><resumen><reservas>${data.totalReservas}</reservas><total>${data.total}</total><pagado>${data.pagado}</pagado><pendiente>${data.pendiente}</pendiente></resumen><registros>${data.detail.map((r:any)=>`<registro>${Object.entries(r).map(([k,v])=>`<${k}>${escXml(v)}</${k}>`).join('')}</registro>`).join('')}</registros></informe_financiero>`;}
async function pdf(data:any){const doc=await PDFDocument.create();const regular=await doc.embedFont(StandardFonts.Helvetica);const bold=await doc.embedFont(StandardFonts.HelveticaBold);const W=841.89,H=595.28,margin=34;let page:any,y=0;const add=()=>{page=doc.addPage([W,H]);y=H-38;page.drawText('ALEMSI · Mamuil Malal',{x:margin,y,size:9,font:bold,color:rgb(.05,.18,.14)});y-=22;page.drawText('Informe financiero',{x:margin,y,size:20,font:bold,color:rgb(.05,.18,.14)});y-=18;page.drawText(`Periodo: ${data.filters.desde||'Todos'} a ${data.filters.hasta||'Todos'}   Institucion: ${data.filters.institucion||'Todas'}   Estado: ${data.filters.estado||'Todos'}`,{x:margin,y,size:8,font:regular,color:rgb(.35,.4,.38)});y-=25;};add();page.drawText(`Reservas: ${data.totalReservas}    Total: $${data.total.toLocaleString('es-CL')}    Pagado: $${data.pagado.toLocaleString('es-CL')}    Pendiente: $${data.pendiente.toLocaleString('es-CL')}`,{x:margin,y,size:10,font:bold});y-=24;const widths=[86,64,92,75,65,60,55,170,65];const headers=['Codigo','RUT','Comensal','Institucion','Fecha','Servicio','Estado','Plato / opcion','Monto'];const drawHeader=()=>{let x=margin;headers.forEach((h,i)=>{page.drawText(h,{x,y,size:7,font:bold});x+=widths[i]});y-=13;page.drawLine({start:{x:margin,y:y+5},end:{x:W-margin,y:y+5},thickness:.6});};drawHeader();for(const r of data.detail){if(y<42){add();drawHeader();}const vals=[r.codigo_reserva,r.rut,r.comensal,r.institucion,r.fecha,r.servicio,r.estado_visible,`${r.plato}${r.opcion?` · ${r.opcion}`:''}`,`$${Number(r.valor_servicio||0).toLocaleString('es-CL')}`];let x=margin;vals.forEach((v,i)=>{let s=String(v||'');const max=Math.max(4,Math.floor(widths[i]/4.5));if(s.length>max)s=s.slice(0,max-1)+'…';page.drawText(s,{x,y,size:6.7,font:regular});x+=widths[i]});y-=13;}return Buffer.from(await doc.save());}
export async function GET(req:NextRequest,{params}:{params:Promise<{formato:string}>}){await requireUser(['Finanzas','AdminTotal']);const {formato}=await params;const data=await financeExportData(filters(req));const stamp=new Date().toISOString().slice(0,10);if(formato==='csv')return new NextResponse(csv(data),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="finanzas-${stamp}.csv"`}});if(formato==='xml')return new NextResponse(xml(data),{headers:{'Content-Type':'application/xml; charset=utf-8','Content-Disposition':`attachment; filename="finanzas-${stamp}.xml"`}});if(formato==='pdf'){const bytes=await pdf(data);return new NextResponse(new Uint8Array(bytes),{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="informe-financiero-${stamp}.pdf"`}});}return NextResponse.json({error:'Formato no soportado'},{status:404});}
