import AppShell from '@/components/AppShell';
import { requireUser } from '@/lib/auth/session';
import { buscarComensalesParaExcepcion,listarExcepcionesPersonas,listarValoresInstituciones } from '@/lib/db/valores-servicio';
import { estadoExcepcionPersonaAction,guardarExcepcionPersonaAction,guardarValorInstitucionAction } from './actions';

export const dynamic='force-dynamic';
const money=(n:number)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(n||0));

export default async function Page({searchParams}:{searchParams:Promise<{q?:string}>}){
  const u=await requireUser(['Finanzas','AdminTotal','AdminCasino','Gerencia']);
  const puedeEditar=u.rol==='Finanzas'||u.rol==='AdminTotal';
  const params=await searchParams;const q=String(params.q||'').trim();
  const [instituciones,excepciones,busqueda]=await Promise.all([listarValoresInstituciones(),listarExcepcionesPersonas(),q?buscarComensalesParaExcepcion(q):Promise.resolve([])]);
  return <AppShell user={u}><div className="space-y-5">
    <section><p className="text-xs font-extrabold tracking-[.18em] text-[#1DB954]">VALORES DEL SERVICIO</p><h1 className="text-2xl font-black text-[#0E2A23]">Maestro de valores y excepciones</h1><p className="mt-1 text-sm text-[#6B7570]">La reserva aplica esta prioridad: excepción por persona → regla especial de institución → valor normal de institución. El monto queda congelado en la reserva al confirmarla.</p></section>
    {!puedeEditar&&<div className="rounded-xl border border-[#D4AF37]/40 bg-[#D4AF37]/10 p-3 text-sm"><b>Modo consulta.</b> Finanzas administra los valores. Este perfil puede revisar qué regla está vigente.</div>}

    <section className="rounded-2xl border bg-white p-4 sm:p-5"><div className="mb-4"><h2 className="text-lg font-black">Valores por institución</h2><p className="text-sm text-[#6B7570]">El valor especial institucional solo se usa cuando su regla está activa.</p></div><div className="space-y-3">{instituciones.map((r:any)=><form key={r.nombre} action={guardarValorInstitucionAction} className="grid gap-3 rounded-xl border p-3 lg:grid-cols-[1.2fr_.7fr_.7fr_.7fr_1.5fr_auto] lg:items-end"><input type="hidden" name="nombre" value={r.nombre}/><div><div className="font-black">{r.nombre}</div><div className="text-xs text-[#6B7570]">{Number(r.activa)===1?'Institución activa':'Institución inactiva'} · actual {money(Number(r.regla_activa)&&r.precio_especial!=null?r.precio_especial:r.precio_dia)}</div></div><label className="text-xs font-bold">Valor normal<input name="precio_dia" type="number" min="0" defaultValue={Number(r.precio_dia||0)} disabled={!puedeEditar} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm font-normal disabled:bg-gray-50"/></label><label className="text-xs font-bold">Valor especial<input name="precio_especial" type="number" min="0" defaultValue={r.precio_especial==null?'':Number(r.precio_especial)} disabled={!puedeEditar} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm font-normal disabled:bg-gray-50"/></label><label className="text-xs font-bold">Regla especial<select name="regla_activa" defaultValue={Number(r.regla_activa)===1?'1':'0'} disabled={!puedeEditar} className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm font-normal disabled:bg-gray-50"><option value="0">No</option><option value="1">Sí</option></select></label><label className="text-xs font-bold">Descripción<input name="descripcion" defaultValue={r.descripcion||''} disabled={!puedeEditar} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm font-normal disabled:bg-gray-50"/></label>{puedeEditar?<button className="rounded-lg bg-[#0E2A23] px-4 py-2 text-sm font-black text-white">Guardar</button>:<span className="text-xs text-[#6B7570]">Solo lectura</span>}</form>)}</div></section>

    <section className="rounded-2xl border bg-white p-4 sm:p-5"><div className="mb-4"><h2 className="text-lg font-black">Excepciones por persona</h2><p className="text-sm text-[#6B7570]">Una excepción activa por RUT reemplaza cualquier valor de su institución solo para reservas nuevas.</p></div>
      {puedeEditar&&<><form className="flex flex-col gap-2 sm:flex-row"><input name="q" defaultValue={q} placeholder="Buscar por RUT, nombre o institución" className="min-h-11 flex-1 rounded-lg border px-3"/><button className="rounded-lg border px-4 py-2 font-bold">Buscar comensal</button></form>{q&&<div className="mt-3 space-y-2">{busqueda.length?busqueda.map((p:any)=><form key={p.rut} action={guardarExcepcionPersonaAction} className="grid gap-2 rounded-xl border p-3 md:grid-cols-[1.2fr_.8fr_1.2fr_auto] md:items-end"><input type="hidden" name="rut" value={p.rut}/><input type="hidden" name="activa" value="1"/><div><b>{p.nombre}</b><div className="text-xs text-[#6B7570]">{p.rut} · {p.institucion||'Sin institución'}</div></div><label className="text-xs font-bold">Valor especial<input required name="precio_especial" type="number" min="0" className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"/></label><label className="text-xs font-bold">Motivo / descripción<input required name="descripcion" className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" placeholder="Motivo de la excepción"/></label><button className="rounded-lg bg-[#1DB954] px-4 py-2 font-black">Aplicar excepción</button></form>):<p className="text-sm text-[#6B7570]">No se encontraron comensales.</p>}</div>}</>}
      <div className="mt-5 overflow-x-auto"><table className="min-w-[760px] w-full text-sm"><thead><tr className="border-b text-left"><th className="py-2">Persona</th><th>Institución</th><th>Valor especial</th><th>Estado</th><th>Descripción</th><th>Última actualización</th><th></th></tr></thead><tbody>{excepciones.map((e:any)=><tr key={e.rut} className="border-b"><td className="py-3"><b>{e.nombre||'—'}</b><div className="text-xs text-[#6B7570]">{e.rut}</div></td><td>{e.institucion||'—'}</td><td className="font-bold">{money(e.precio_especial)}</td><td>{Number(e.activa)===1?'Activa':'Inactiva'}</td><td>{e.descripcion||'—'}</td><td className="text-xs">{e.actualizado_por||'—'}{e.actualizado_at?<><br/>{String(e.actualizado_at).slice(0,16).replace('T',' ')}</>:null}</td><td>{puedeEditar&&<form action={estadoExcepcionPersonaAction}><input type="hidden" name="rut" value={e.rut}/><input type="hidden" name="activa" value={Number(e.activa)===1?'0':'1'}/><button className="rounded-lg border px-3 py-1.5 font-bold">{Number(e.activa)===1?'Desactivar':'Activar'}</button></form>}</td></tr>)}</tbody></table>{!excepciones.length&&<p className="py-4 text-sm text-[#6B7570]">No hay excepciones individuales configuradas.</p>}</div>
    </section>
  </div></AppShell>;
}
