import Link from 'next/link';
import AppShell from '@/components/AppShell';
import PrintProductionReportButton from '@/components/PrintProductionReportButton';
import { requireUser } from '@/lib/auth/session';
import { detalleProduccionFecha } from '@/lib/db/produccion-vista';
import { enviarReporteProduccionAction } from './actions';

export const dynamic='force-dynamic';
function fechaChile(date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);}
function fechaValida(value?:string){return Boolean(value&&/^\d{4}-\d{2}-\d{2}$/.test(value));}
function fechaVisible(iso:string){const [y,m,d]=iso.split('-');return `${d}-${m}-${y}`;}
function opcionCorta(v?:string){const s=String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();if(s.includes('OPCION 1'))return'Op. 1';if(s.includes('OPCION 2'))return'Op. 2';if(s.includes('HIPO'))return'Hip.';return v||'—';}

export default async function Page({searchParams}:{searchParams:Promise<{fecha?:string;origen?:string;envio?:string}>}){
 const u=await requireUser(['Cocina','AdminCasino','AdminTotal','Gerencia']); const q=await searchParams;const fecha=fechaValida(q.fecha)?q.fecha!:fechaChile(); const origen=q.origen==='admin'?'admin':q.origen==='gerencia'?'gerencia':'cocina';const volver=origen==='admin'?`/admin-casino/produccion?fecha=${fecha}`:origen==='gerencia'?'/gerencia':`/cocina?fecha=${fecha}`;const rows=await detalleProduccionFecha(fecha); const servicios=[...new Set(rows.map(r=>r.servicio))]; const comensales=new Set(rows.map(r=>r.rut)).size; const raciones=rows.length;
 return <AppShell user={u}><style>{`@page{size:Letter portrait;margin:7mm}@media print{.app-shell-nav,nav,aside,.print-hide{display:none!important}body{font-size:8pt;line-height:1.15}.report-page{max-width:none!important;margin:0!important}.dish-card{break-inside:avoid!important;page-break-inside:avoid!important}.person-line{font-size:7pt!important;padding:0.6mm 0!important}}`}</style><div className="report-page mx-auto max-w-5xl space-y-4">
  <section className="bg-white"><div className="border-b-2 border-[#0B3B78] px-4 py-3 text-center print:px-0 print:py-2"><div className="text-[20px] font-black text-[#0B3B78] print:text-[15pt]">ALEMSI · CASINO MAMUIL</div><div className="mt-1 text-[17px] font-black text-[#0B3B78] print:text-[12pt]">REPORTE DIARIO DE PRODUCCIÓN</div></div><div className="grid grid-cols-3 border-x border-b border-[#cbd9d3] text-sm print:text-[8pt]"><div className="p-2"><b>Fecha</b><br/>{fechaVisible(fecha)}</div><div className="p-2 text-center"><b>Comensales del día</b><br/><span className="text-lg font-black">{comensales}</span></div><div className="p-2 text-right"><b>Raciones a producir</b><br/><span className="text-lg font-black">{raciones}</span></div></div><div className="print-hide mt-3 flex flex-wrap items-end justify-between gap-3"><div className="flex gap-2"><Link href={volver} className="rounded-lg border px-4 py-2 text-sm font-black">← Volver</Link><PrintProductionReportButton/></div><form className="flex items-end gap-2"><input type="hidden" name="origen" value={origen}/><label className="text-sm font-bold">Fecha<input type="date" name="fecha" defaultValue={fecha} className="ml-2 rounded-lg border p-2"/></label><button className="rounded-lg bg-[#0B2D5B] px-4 py-2 font-bold text-white">Ver día</button></form></div></section>
  {u.rol!=='Gerencia'&&q.envio&&<div className="print-hide rounded-xl border p-3 text-sm font-bold">{q.envio==='ok'?'Reporte enviado por correo correctamente.':`Estado de envío: ${q.envio}`}</div>}
  {u.rol!=='Gerencia'&&<section className="print-hide rounded-xl border bg-white p-4"><form action={enviarReporteProduccionAction} className="flex flex-wrap items-end gap-2"><input type="hidden" name="fecha" value={fecha}/><input type="hidden" name="origen" value={origen}/><label className="text-sm font-bold">Enviar reporte a<input type="email" name="correo" required placeholder="correo@empresa.cl" className="ml-2 rounded-lg border p-2"/></label><button disabled={!rows.length} className="rounded-lg bg-[#087A46] px-4 py-2 font-black text-white disabled:opacity-40">Enviar correo</button></form></section>}
  {!rows.length&&<section className="rounded border p-4">No hay reservas activas con plato para esta fecha.</section>}
  {servicios.map(servicio=>{const sr=rows.filter(r=>r.servicio===servicio);const grupos=[...new Set(sr.map(r=>`${r.tipo_opcion||'Sin opción'}|||${r.plato}`))];return <section key={servicio} className="bg-white"><div className="mb-2 flex items-center gap-2 border-b-2 border-[#0D9B91] pb-1"><h2 className="text-lg font-black">{servicio.toUpperCase()}</h2><span className="text-sm font-black text-[#0D9B91]">· {sr.length} RACIONES</span></div><div className="grid gap-3 md:grid-cols-2 print:grid-cols-2">{grupos.map(key=>{const [opcion,plato]=key.split('|||');const pr=sr.filter(r=>(r.tipo_opcion||'Sin opción')===opcion&&r.plato===plato);const instituciones=[...new Set(pr.map(r=>r.institucion))].sort((a,b)=>a.localeCompare(b,'es'));return <article key={key} className="dish-card rounded-lg border border-[#cbd9d3] p-3"><div className="flex items-start justify-between gap-2"><div><div className="text-[10px] font-black text-[#0D9B91]">{opcionCorta(opcion)}</div><h3 className="text-sm font-black text-[#0B2D5B]">{plato}</h3></div><b className="text-sm">{pr.length}</b></div><div className="mt-2 grid gap-2 sm:grid-cols-2">{instituciones.map(inst=>{const personas=pr.filter(r=>r.institucion===inst).sort((a,b)=>a.nombre.localeCompare(b.nombre,'es'));return <div key={inst} className="rounded-md bg-[#F7FAF8] p-2"><div className="mb-1 text-[10px] font-black uppercase text-[#0B3B78]">{inst}</div>{personas.map((p,i)=><div key={`${p.rut}-${i}`} className="person-line border-t border-[#e2ebe6] py-1 text-xs first:border-t-0">{p.nombre}</div>)}</div>})}</div></article>})}</div></section>})}
  <footer className="border-t border-[#9fb9ae] py-2 text-center text-xs font-bold text-[#52615b]">ALEMSI · Casino Mamuil · Producción diaria</footer>
 </div></AppShell>;
}
