import AppShell from '@/components/AppShell';
import { requireUser } from '@/lib/auth/session';
import { dashboardGerencia } from '@/lib/db/gerencia';

export const dynamic='force-dynamic';
export default async function Page(){
  const u=await requireUser(['Gerencia','AdminTotal']); const d=await dashboardGerencia();
  return <AppShell user={u}><div className="space-y-5"><section><p className="text-xs font-extrabold tracking-[.18em] text-[#1DB954]">GERENCIA · SOLO CONSULTA</p><h1 className="text-2xl font-black">Resumen ejecutivo</h1></section><section className="grid gap-3 md:grid-cols-4">{[['Reservas futuras',d.resumen.reservas],['Raciones futuras',d.resumen.raciones],['Valor asociado',`$${Number(d.resumen.monto||0).toLocaleString('es-CL')}`],['Lotes con stock',d.bodega.con_stock]].map(([label,value])=><div key={String(label)} className="rounded-2xl border bg-white p-5"><div className="text-sm text-[#6B7570]">{label}</div><div className="text-3xl font-black">{String(value||0)}</div></div>)}</section><section className="grid gap-5 lg:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Finanzas</h2><div className="mt-3 space-y-2">{d.pagos.map((r:any)=><div key={r.estado} className="rounded-xl bg-[#F6F3EA] p-3"><b>{r.estado}</b><div>{r.cantidad} registros · ${Number(r.monto||0).toLocaleString('es-CL')}</div></div>)}</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Producción</h2><div className="mt-3 space-y-2">{d.jornadas.map((r:any)=><div key={r.estado} className="rounded-xl bg-[#F6F3EA] p-3"><b>{r.estado}</b><div>{r.cantidad} jornadas</div></div>)}</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Minutas oficiales</h2><div className="mt-3 space-y-2">{d.minutas.map((r:any)=><div key={r.estado} className="rounded-xl bg-[#F6F3EA] p-3"><b>{r.estado}</b><div>{r.cantidad} registros</div></div>)}</div></div></section><section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Reporte consolidado de raciones</h2><div className="mt-3 grid gap-2 md:grid-cols-3">{d.produccion.map((r:any,i:number)=><div key={i} className="rounded-xl bg-[#F6F3EA] p-3"><b>{r.fecha} · {r.servicio}</b><div>{r.cantidad} raciones</div></div>)}</div></section><section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Última auditoría</h2><div className="mt-3 space-y-2 text-sm">{d.auditoria.map((r:any,i:number)=><div key={i} className="border-b pb-2"><b>{r.accion}</b> · {r.usuario} · {r.fecha}</div>)}</div></section></div></AppShell>;
}
