import type { MinutaRow } from '@/lib/db/minutas';

const ORDEN_SERVICIO=['Desayuno','Almuerzo','Once','Cena'];
function hoyChile(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function fechaLarga(fecha:string){const [y,m,d]=fecha.split('-').map(Number);if(!y||!m||!d)return fecha;return new Intl.DateTimeFormat('es-CL',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'America/Santiago'}).format(new Date(Date.UTC(y,m-1,d,12)));}
function fechaCorta(fecha:string){const [y,m,d]=fecha.split('-').map(Number);if(!y||!m||!d)return fecha;return new Intl.DateTimeFormat('es-CL',{weekday:'short',day:'2-digit',month:'2-digit',timeZone:'America/Santiago'}).format(new Date(Date.UTC(y,m-1,d,12)));}
function opcionCorta(v?:string|null){const s=String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();if(s.includes('OPCION 1'))return'Op. 1';if(s.includes('OPCION 2'))return'Op. 2';if(s.includes('HIPO'))return'Hip.';return v||'—';}
function fechasRango(inicio:string,fin:string){const fechas:string[]=[];for(let fecha=inicio;fecha<=fin;){fechas.push(fecha);const [y,m,d]=fecha.split('-').map(Number);fecha=new Date(Date.UTC(y,m-1,d+1)).toISOString().slice(0,10);}return fechas;}

export default function MinutaPublicada({rows,empty='No existe minuta publicada para el período.',compactWeekly=false,inicio,fin}:{rows:MinutaRow[];empty?:string;compactWeekly?:boolean;inicio?:string;fin?:string}){
  const hoy=hoyChile();const fechas=inicio&&fin?fechasRango(inicio,fin):[...new Set(rows.map(row=>String(row.fecha)))].sort();
  if(compactWeekly){
    return <div className="mt-3">
      {!!fechas.length&&<div className="overflow-x-auto pb-2"><div className="grid min-w-[980px] gap-2" style={{gridTemplateColumns:`repeat(${fechas.length}, minmax(138px, 1fr))`}}>{fechas.map(fecha=>{const filas=rows.filter(row=>String(row.fecha)===fecha);const servicios=[...new Set(filas.map(row=>row.servicio))].sort((a,b)=>{const ia=ORDEN_SERVICIO.indexOf(a),ib=ORDEN_SERVICIO.indexOf(b);return(ia<0?99:ia)-(ib<0?99:ib);});const esHoy=fecha===hoy;return <article key={fecha} className={`rounded-lg border p-2 ${esHoy?'border-[#1DB954] bg-[#1DB954]/5':'border-[#A6B0AA]/25 bg-[#FFFDF8]'}`}><div className="mb-2 flex items-center justify-between gap-1 border-b border-[#A6B0AA]/20 pb-1.5"><div className="text-[11px] font-black capitalize text-[#0E2A23]">{fechaCorta(fecha)}</div>{esHoy&&<span className="rounded-full bg-[#1DB954] px-1.5 py-0.5 text-[9px] font-black">HOY</span>}</div><div className="space-y-2">{servicios.map(servicio=>{const opciones=filas.filter(row=>row.servicio===servicio);return <div key={servicio}><div className="mb-1 text-[10px] font-black uppercase tracking-wide text-[#0B3B78]">{servicio}</div><div className="space-y-1">{opciones.map((row,i)=><div key={`${row.servicio}-${row.tipo_opcion}-${row.plato}-${i}`} className="rounded-md bg-white px-2 py-1.5 shadow-sm"><div className="text-[9px] font-extrabold text-[#0D9B91]">{opcionCorta(row.tipo_opcion)}</div><div className="mt-0.5 text-[11px] font-bold leading-tight text-[#0E2A23]">{row.plato}</div></div>)}</div></div>})}{!filas.length&&<p className="rounded-md bg-[#F6F3EA] px-2 py-3 text-center text-[10px] font-bold text-[#6B7570]">Sin minuta publicada</p>}</div></article>})}</div></div>}
      {!fechas.length&&<p className="rounded-xl bg-[#F6F3EA] p-4 text-sm text-[#6B7570]">{empty}</p>}
    </div>;
  }
  return <div className="mt-4 space-y-5">{fechas.map(fecha=>{const filas=rows.filter(row=>String(row.fecha)===fecha);const servicios=[...new Set(filas.map(row=>row.servicio))].sort((a,b)=>{const ia=ORDEN_SERVICIO.indexOf(a),ib=ORDEN_SERVICIO.indexOf(b);return(ia<0?99:ia)-(ib<0?99:ib);});const esHoy=fecha===hoy;return <section key={fecha} className={`overflow-hidden rounded-2xl border bg-white shadow-sm ${esHoy?'border-[#1DB954] ring-2 ring-[#1DB954]/20':'border-[#A6B0AA]/30'}`}><header className={`flex flex-wrap items-center justify-between gap-3 px-5 py-4 ${esHoy?'bg-[#1DB954]/10':'bg-[#F6F3EA]'}`}><div><div className="text-xs font-extrabold uppercase tracking-[.16em] text-[#6B7570]">Minuta publicada</div><h3 className="mt-1 text-xl font-black capitalize text-[#0E2A23]">{fechaLarga(fecha)}</h3></div><div className="flex items-center gap-2">{esHoy&&<span className="rounded-full bg-[#1DB954] px-3 py-1 text-xs font-black text-[#071814]">HOY</span>}<span className="rounded-full border border-[#A6B0AA]/40 bg-white px-3 py-1 text-xs font-bold text-[#6B7570]">{fecha}</span></div></header><div className="grid gap-4 p-5 lg:grid-cols-2">{servicios.map(servicio=>{const opciones=filas.filter(row=>row.servicio===servicio);return <article key={servicio} className="rounded-2xl border border-[#A6B0AA]/25 bg-[#FFFDF8] p-4"><div className="mb-3 flex items-center justify-between gap-3 border-b border-[#A6B0AA]/20 pb-3"><h4 className="text-lg font-black uppercase tracking-wide text-[#0E2A23]">{servicio}</h4><span className="text-xs font-bold text-[#6B7570]">{opciones.length} opción(es)</span></div><div className="space-y-3">{opciones.map((row,index)=><div key={`${row.servicio}-${row.tipo_opcion}-${row.plato}-${index}`} className="rounded-xl bg-white p-3 shadow-sm"><div className="text-xs font-extrabold tracking-wider text-[#1DB954]">{opcionCorta(row.tipo_opcion)}</div><div className="mt-1 text-base font-black text-[#0E2A23]">{row.plato}</div></div>)}</div></article>})}</div></section>})}{!rows.length&&<p className="rounded-2xl bg-[#F6F3EA] p-5 text-sm text-[#6B7570]">{empty}</p>}</div>;
}
