import React from 'react';

type Row={id?:number;fecha:string;servicio:string;tipo_opcion?:string|null;plato:string;estado?:string;cantidad?:number|string;instituciones?:Array<{institucion:string;cantidad:number;comensales?:string[]}>};
const fmt=(v:string)=>{const [y,m,d]=String(v).slice(0,10).split('-');return y&&m&&d?`${d}-${m}-${y}`:v};
const order=['Desayuno','Almuerzo','Once','Cena'];
export default function MinutaDemandCalendar({rows,title='Minuta y demanda'}:{rows:Row[];title?:string}){
 const days=[...new Set(rows.map(r=>String(r.fecha).slice(0,10)))].sort();
 return <section className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-5"><div className="mb-4"><h2 className="text-xl font-black text-[#0E2A23]">{title}</h2><p className="text-sm text-[#6B7570]">Vista compacta. Abre un día, luego un plato y finalmente una institución para ver el detalle sin salir de la página.</p></div>
 <div className="overflow-x-auto pb-2"><div className="flex min-w-max gap-3">{days.map(day=>{const dr=rows.filter(r=>String(r.fecha).slice(0,10)===day);const total=dr.reduce((s,r)=>s+Number(r.cantidad||0),0);return <details key={day} className="w-[310px] shrink-0 rounded-2xl border border-[#A6B0AA]/35 bg-[#FFFDF8] p-4" open={days.length<=2}><summary className="cursor-pointer list-none"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-extrabold tracking-wider text-[#1DB954]">DÍA</div><div className="text-lg font-black">{fmt(day)}</div></div><div className="rounded-xl bg-[#0E2A23] px-3 py-2 text-right text-white"><div className="text-xs">Raciones</div><b>{total}</b></div></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs">{order.map(s=><div key={s} className="rounded-lg bg-[#F6F3EA] p-2"><b>{s}</b><div>{dr.filter(r=>r.servicio===s).reduce((n,r)=>n+Number(r.cantidad||0),0)} raciones</div></div>)}</div></summary>
 <div className="mt-4 space-y-3 border-t pt-3">{order.map(servicio=>{const sr=dr.filter(r=>r.servicio===servicio);if(!sr.length)return null;return <div key={servicio}><h3 className="mb-2 font-black text-[#0E2A23]">{servicio}</h3>{sr.map((r,i)=><details key={`${r.id||i}-${r.plato}`} className="mb-2 rounded-xl border bg-white p-3"><summary className="cursor-pointer list-none"><div className="flex justify-between gap-3"><div><b>{r.tipo_opcion||'Opción'}</b><div>{r.plato}</div></div><span className="rounded-full bg-[#1DB954]/10 px-2 py-1 font-black">{Number(r.cantidad||0)}</span></div></summary>{(r.instituciones||[]).length?<div className="mt-3 space-y-2 border-t pt-2">{r.instituciones!.map(inst=><details key={inst.institucion} className="rounded-lg bg-[#F6F3EA] p-2"><summary className="cursor-pointer font-bold">{inst.institucion} · {inst.cantidad}</summary>{inst.comensales?.length?<ul className="mt-2 space-y-1 text-sm">{inst.comensales.map((n,j)=><li key={j}>• {n}</li>)}</ul>:<div className="mt-2 text-sm text-[#6B7570]">Sin nombres para mostrar.</div>}</details>)}</div>:<div className="mt-2 text-xs text-[#6B7570]">Sin reservas asociadas todavía.</div>}</details>)}</div>})}</div></details>})}</div></div>{!days.length&&<div className="rounded-xl bg-[#F6F3EA] p-4 text-sm">No hay minuta para el período.</div>}</section>
}
