import 'server-only';
import { listarFinanzas } from '@/lib/db/finanzas';
import { estadoBandeja } from '@/lib/reglas/finanzas';

export type FinanceFilters={desde?:string;hasta?:string;institucion?:string;medio?:string;q?:string;estado?:string};
const paid=(r:any)=>['PAGADO','APROBADO'].includes(String(r.estado_pago||'').trim().toUpperCase())||String(r.comprobante_estado||'').toUpperCase()==='VALIDADO';
const services=(r:any)=>Array.isArray(r.servicios)?r.servicios:[];
const hasProof=(r:any)=>Boolean(r.comprobante_id);
const proofState=(r:any)=>String(r.comprobante_estado||'').trim().toUpperCase();
const proofPending=(r:any)=>hasProof(r)&&!['VALIDADO','RECHAZADO'].includes(proofState(r));
const chargeable=(r:any)=>!['NO APLICA','COSTO ASUMIDO','COSTO ASUMIDO / NO COBRABLE'].includes(String(r.estado_pago||'Pendiente').trim().toUpperCase())&&Number(r.total||0)>0;
export function financeStatus(r:any){if(!hasProof(r)&&paid(r))return 'Pagado · sin comprobante';if(!hasProof(r))return 'Sin comprobante';if(proofPending(r))return 'Comprobante por validar';if(estadoBandeja(r)==='rechazados')return 'Rechazado';return paid(r)?'Validado':'Pendiente';}
function stateMatch(r:any,s='global'){if(s==='global')return true;if(s==='pendientes')return chargeable(r)&&!paid(r);if(s==='sin-comprobante')return !hasProof(r);if(s==='por-validar')return proofPending(r);if(s==='rechazados')return estadoBandeja(r)==='rechazados';if(s==='validados')return paid(r);return true;}
function rangeMatch(r:any,d?:string,h?:string){if(!d&&!h)return true;return services(r).some((s:any)=>(!d||String(s.fecha||'')>=d)&&(!h||String(s.fecha||'')<=h));}
export async function financeExportData(f:FinanceFilters){const rows=await listarFinanzas();const q=String(f.q||'').trim().toLocaleLowerCase('es-CL');const filtered=rows.filter((r:any)=>{if(f.institucion&&String(r.institucion||'')!==f.institucion)return false;if(f.medio&&String(r.metodo_pago||'')!==f.medio)return false;if(q&&!([r.rut,r.nombre,r.codigo_reserva,r.institucion,r.metodo_pago].map(v=>String(v||'').toLocaleLowerCase('es-CL')).join(' ').includes(q)))return false;return rangeMatch(r,f.desde,f.hasta)&&stateMatch(r,f.estado||'global');});const detail=filtered.flatMap((r:any)=>{const ss=services(r).filter((s:any)=>(!f.desde||String(s.fecha||'')>=f.desde!)&&(!f.hasta||String(s.fecha||'')<=f.hasta!));return (ss.length?ss:[{}]).map((s:any)=>({codigo_reserva:r.codigo_reserva||'',rut:r.rut||'',comensal:r.nombre||'',institucion:r.institucion||'',tipo_cliente:r.tipo_cliente||r.tipo_comensal||'',fecha:s.fecha||'',servicio:s.servicio||'',plato:s.plato||'',opcion:s.opcion||'',valor_servicio:Number(s.monto||0),monto_reserva:Number(r.total||0),medio_pago:r.metodo_pago||'',estado_financiero:r.estado_pago||'Pendiente',estado_comprobante:r.comprobante_estado||'Sin comprobante',estado_visible:financeStatus(r),motivo:r.comprobante_motivo||r.motivo_estado_pago||''}));});return{filters:f,rows:filtered,detail,totalReservas:filtered.length,total:filtered.reduce((a:number,r:any)=>a+Number(r.total||0),0),pagado:filtered.filter(paid).reduce((a:number,r:any)=>a+Number(r.total||0),0),pendiente:filtered.filter((r:any)=>chargeable(r)&&!paid(r)).reduce((a:number,r:any)=>a+Number(r.total||0),0)};}
