import AppShell from '@/components/AppShell';
import CierreJornada from '@/components/CierreJornada';
import { requireUser } from '@/lib/auth/session';
import { demandaFecha, detalleJornada, jornada } from '@/lib/db/cocina';
import { iniciarAction } from './actions';
export const dynamic='force-dynamic';
export default async function Page({searchParams}:{searchParams:Promise<{fecha?:string}>}){
  const u=await requireUser(['Cocina','AdminCasino','AdminTotal']); const q=await searchParams;
  const fecha=q.fecha||new Date().toISOString().slice(0,10); const [rows,j,detalle]=await Promise.all([demandaFecha(fecha),jornada(fecha),detalleJornada(fecha)]);
  const estado=String(j?.estado||'Pendiente');
  const total=rows.reduce((sum,row)=>sum+Number(row.reservadas||0),0);
  return <AppShell user={u}><section className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-5"><p className="text-xs font-extrabold tracking-[.18em] text-[#1DB954]">COCINA / PRODUCCIÓN</p><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-black">Producción del día</h1><p className="text-sm text-[#6B7570]">Reserva = demanda. Producción deduplica RUT + fecha + servicio. Bodega solo se descuenta al iniciar jornada.</p></div><form><input type="date" name="fecha" defaultValue={fecha} className="rounded-lg border p-2"/><button className="ml-2 rounded-lg border px-3 py-2 font-bold">Consultar</button></form></div><div className="mt-5 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-[#F6F3EA] p-4"><span className="text-sm">Raciones</span><div className="text-3xl font-black">{total}</div></div><div className="rounded-xl bg-[#F6F3EA] p-4"><span className="text-sm">Preparaciones</span><div className="text-3xl font-black">{rows.length}</div></div><div className="rounded-xl bg-[#F6F3EA] p-4"><span className="text-sm">Jornada</span><div className="text-xl font-black">{estado}</div></div></div><h2 className="mt-5 text-xl font-black">Reporte de demanda por servicio</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{rows.map((r,i)=><div key={i} className="rounded-xl border p-4"><div className="text-xs font-bold text-[#6B7570]">{r.servicio} · {r.tipo_opcion||'—'}</div><div className="font-black">{r.plato}</div><div className="mt-1 text-2xl font-black text-[#0E2A23]">{r.reservadas} porciones</div></div>)}</div><div className="mt-5 rounded-xl bg-[#F6F3EA] p-4"><div className="font-bold">Estado de jornada: {estado}</div>{estado==='Pendiente'&&<form action={iniciarAction} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="fecha" value={fecha}/><label className="flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-sm"><input type="checkbox" name="confirmacion" required/> Confirmo iniciar la jornada completa</label><button className="rounded-lg bg-[#1DB954] px-4 py-2 font-bold">Iniciar jornada</button></form>}{estado==='En producción'&&<CierreJornada fecha={fecha} rows={detalle}/>} {estado==='Finalizado'&&<div className="mt-3 rounded-lg bg-[#1DB954]/10 p-3 font-bold">Jornada finalizada.</div>}</div></section></AppShell>
}
