import Link from 'next/link';
import AppShell from '@/components/AppShell';
import CierreJornada from '@/components/CierreJornada';
import MinutaPublicada from '@/components/MinutaPublicada';
import { requireUser } from '@/lib/auth/session';
import { demandaFecha, detalleJornada, jornada } from '@/lib/db/cocina';
import { detalleProduccionFecha } from '@/lib/db/produccion-vista';
import { obtenerMinutasRango } from '@/lib/db/minutas';
import { iniciarAction } from './actions';

export const dynamic='force-dynamic';
function fechaChile(date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);}
function fechaValida(value?:string){return Boolean(value&&/^\d{4}-\d{2}-\d{2}$/.test(value))}
function opcionCorta(v?:string){const s=String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();if(s.includes('OPCION 1'))return 'Opción 1';if(s.includes('OPCION 2'))return 'Opción 2';if(s.includes('HIPO'))return 'Hipocalórico';return v||'—';}
function ordenOpcion(v?:string){const s=String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();if(s.includes('OPCION 1'))return 1;if(s.includes('OPCION 2'))return 2;if(s.includes('HIPO'))return 3;return 4;}

export default async function Page({searchParams}:{searchParams:Promise<{fecha?:string;inicio?:string;fin?:string}>}){
  const u=await requireUser(['Cocina','AdminCasino','AdminTotal']); const q=await searchParams; const hoy=fechaChile(); const fecha=fechaValida(q.fecha)?q.fecha!:hoy;
  const finDefaultDate=new Date();finDefaultDate.setDate(finDefaultDate.getDate()+6);const inicio=fechaValida(q.inicio)?q.inicio!:hoy;const fin=fechaValida(q.fin)&&q.fin!>=inicio?q.fin!:fechaChile(finDefaultDate);
  const [rows,j,detalle,minuta,personas]=await Promise.all([demandaFecha(fecha),jornada(fecha),detalleJornada(fecha),obtenerMinutasRango(inicio,fin),detalleProduccionFecha(fecha)]);
  const estado=String(j?.estado||'Pendiente'); const raciones=personas.length; const comensales=new Set(personas.map(r=>String(r.rut||'').trim()).filter(Boolean)).size; const servicios=[...new Set(personas.map(r=>r.servicio))];
  return <AppShell user={u}><div className="space-y-5">
    <section className="rounded-2xl border bg-white p-4 sm:p-5">
      <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-extrabold tracking-[.18em] text-[#1DB954]">MINUTA DE TRABAJO</p><h1 className="text-2xl font-black text-[#0E2A23]">Minuta oficial publicada</h1><p className="mt-1 text-sm text-[#6B7570]">Fuente única publicada por Admin Casino. Vista operativa para Cocina.</p></div><form className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="fecha" value={fecha}/><label className="text-xs font-bold">Desde<input type="date" name="inicio" defaultValue={inicio} className="mt-1 block rounded-lg border p-1.5 text-sm"/></label><label className="text-xs font-bold">Hasta<input type="date" name="fin" defaultValue={fin} className="mt-1 block rounded-lg border p-1.5 text-sm"/></label><button className="self-end rounded-lg border px-3 py-1.5 text-sm font-bold">Ver período</button></form></div>
      <MinutaPublicada rows={minuta} compactWeekly/>
    </section>

    <section className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-5"><p className="text-xs font-extrabold tracking-[.18em] text-[#1DB954]">COCINA / PRODUCCIÓN</p><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-black">Producción del día</h2><p className="text-sm text-[#6B7570]">Comensales únicos y raciones son indicadores distintos. Cada selección de servicio equivale a una ración.</p></div><div className="flex flex-wrap items-end gap-2"><form className="flex items-end gap-2"><input type="hidden" name="inicio" value={inicio}/><input type="hidden" name="fin" value={fin}/><label className="text-sm font-bold">Día de producción<input type="date" name="fecha" defaultValue={fecha} className="mt-1 block rounded-lg border p-2"/></label><button className="rounded-lg border px-3 py-2 font-bold">Ver día</button></form><Link href={`/produccion/reporte?fecha=${encodeURIComponent(fecha)}&origen=cocina`} className="rounded-lg border border-[#0D9B91] px-4 py-2 text-sm font-black text-[#0D9B91]">Vista reporte</Link><a href={`/api/produccion/reporte-pdf?fecha=${encodeURIComponent(fecha)}`} target="_blank" rel="noreferrer" className="rounded-lg bg-[#0B3B78] px-4 py-2 text-sm font-black text-white">Generar PDF</a></div></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[#F6F3EA] p-4"><span className="text-sm">Comensales del día</span><div className="text-3xl font-black">{comensales}</div></div><div className="rounded-xl bg-[#F6F3EA] p-4"><span className="text-sm">Raciones a producir</span><div className="text-3xl font-black">{raciones}</div></div><div className="rounded-xl bg-[#F6F3EA] p-4"><span className="text-sm">Jornada</span><div className="text-xl font-black">{estado}</div></div></div>
      <h3 className="mt-5 text-lg font-black">Demanda por preparación</h3><div className="mt-3 grid gap-2 md:grid-cols-2">{rows.map((r,i)=><div key={i} className="rounded-lg border border-[#A6B0AA]/30 px-3 py-2"><div className="text-[11px] font-black text-[#0D9B91]">{r.servicio} · {opcionCorta(r.tipo_opcion)}</div><div className="mt-0.5 flex items-start justify-between gap-3"><div className="text-sm font-bold text-[#0E2A23]">{r.plato}</div><div className="shrink-0 text-sm font-black">{r.reservadas}</div></div></div>)}</div>
    </section>

    <section className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-5"><div><p className="text-xs font-extrabold tracking-[.18em] text-[#1DB954]">DETALLE OPERATIVO</p><h2 className="text-xl font-black">Comensales por preparación</h2><p className="mt-1 text-sm text-[#6B7570]">Servicio → opción/plato → institución → comensales. Primero se consolida la producción y luego se muestra quién compone cada total.</p></div>{!personas.length&&<div className="mt-4 rounded-xl bg-[#F6F3EA] p-4 text-sm font-bold">No hay comensales con plato reservado para esta fecha.</div>}<div className="mt-4 space-y-5">{servicios.map(servicio=>{const sr=personas.filter(r=>r.servicio===servicio);const platos=[...new Set(sr.map(r=>`${r.tipo_opcion}|||${r.plato}`))].sort((a,b)=>{const [oa,pa]=a.split('|||');const [ob,pb]=b.split('|||');return ordenOpcion(oa)-ordenOpcion(ob)||pa.localeCompare(pb,'es')});return <div key={servicio}><div className="mb-2 flex items-center gap-2 border-b border-[#A6B0AA]/30 pb-2"><h3 className="text-lg font-black">{servicio.toUpperCase()}</h3><span className="text-sm font-black text-[#0D9B91]">· {sr.length} RACIONES</span></div><div className="grid gap-3 lg:grid-cols-2">{platos.map(key=>{const [opcion,plato]=key.split('|||');const pr=sr.filter(r=>r.tipo_opcion===opcion&&r.plato===plato);const insts=[...new Set(pr.map(r=>r.institucion))].sort((a,b)=>a.localeCompare(b,'es'));return <article key={key} className="rounded-xl border border-[#A6B0AA]/30 bg-white p-3"><div className="flex items-start justify-between gap-3"><div><div className="text-[11px] font-black text-[#0D9B91]">{opcionCorta(opcion)}</div><div className="text-sm font-black text-[#0E2A23]">{plato}</div></div><div className="shrink-0 text-sm font-black">{pr.length}</div></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{insts.map(inst=>{const ps=pr.filter(r=>r.institucion===inst).sort((a,b)=>a.nombre.localeCompare(b.nombre,'es'));return <div key={inst} className="rounded-lg bg-[#F7FAF8] p-2"><div className="mb-1 flex items-center justify-between gap-2 text-[11px] font-black uppercase text-[#0B3B78]"><span>{inst}</span><span>{ps.length} {ps.length===1?'ración':'raciones'}</span></div><ul className="space-y-0.5">{ps.map((p,i)=><li key={`${p.rut}-${i}`} className="text-xs text-[#35443E]">{p.nombre}</li>)}</ul></div>})}</div></article>})}</div></div>})}</div></section>

    <section className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-5"><p className="text-xs font-extrabold tracking-[.18em] text-[#1DB954]">CIERRE DE JORNADA</p><h2 className="text-xl font-black">Cierre y novedades</h2><p className="mt-1 text-sm text-[#6B7570]">Registra el cierre operativo de la jornada y sus diferencias.</p><div className="mt-4 rounded-xl bg-[#F6F3EA] p-4"><div className="font-bold">Estado de jornada: {estado}</div>{estado==='Pendiente'&&<form action={iniciarAction} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="fecha" value={fecha}/><label className="flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-sm"><input type="checkbox" name="confirmacion" required/> Confirmo iniciar la jornada completa</label><button className="rounded-lg bg-[#1DB954] px-4 py-2 font-bold">Iniciar jornada</button></form>}{estado==='En producción'&&<CierreJornada fecha={fecha} rows={detalle}/>} {estado==='Finalizado'&&<div className="mt-3 rounded-lg bg-[#1DB954]/10 p-3 font-bold">Jornada finalizada.</div>}</div></section>
  </div></AppShell>
}
