import Link from 'next/link';
import AppShell from '@/components/AppShell';
import MinutaCarga from '@/components/MinutaCarga';
import MinutaPublicada from '@/components/MinutaPublicada';
import ReclamosGestion from '@/components/ReclamosGestion';
import { requireUser } from '@/lib/auth/session';
import { getReglas, minutasPeriodo, platosDisponibles, resumenAdmin } from '@/lib/db/admin';
import { listarSolicitudesExtraordinarias } from '@/lib/db/solicitudes-extraordinarias';
import { minutaAction, reglasAction, resolverSolicitudExtraordinariaAction } from './actions';
import { responsableReclamoAction } from './actions';
import { listarReclamosParaRol, listarResponsablesReclamos, resumenReclamosJornada } from '@/lib/db/reclamos';
import { listarEncuestasRecientes, resumenSatisfaccion } from '@/lib/db/satisfaccion';

export const dynamic='force-dynamic';
function iso(d:Date){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function cicloViernesJueves(){const hoy=iso(new Date());const [y,m,d]=hoy.split('-').map(Number);const base=new Date(Date.UTC(y,m-1,d,12));const retro=(base.getUTCDay()-5+7)%7;const ini=new Date(base);ini.setUTCDate(base.getUTCDate()-retro);const fin=new Date(ini);fin.setUTCDate(ini.getUTCDate()+6);return [ini.toISOString().slice(0,10),fin.toISOString().slice(0,10)] as const;}
function fechaValida(value?:string){return Boolean(value&&/^\d{4}-\d{2}-\d{2}$/.test(value))}
const tabs=[['minuta','Minuta'],['jornada','Inicio / cierre de jornada'],['reclamos','Reclamos'],['satisfaccion','Satisfacción'],['solicitudes','Solicitudes / excepciones'],['reglas','Reglas de reserva'],['historico','Histórico']] as const;
type Tab=(typeof tabs)[number][0];

export default async function Page({searchParams}:{searchParams:Promise<{inicio?:string;fin?:string;tab?:string}>}){
  const u=await requireUser(['AdminCasino','AdminTotal']);
  const params=await searchParams;const vigenteRango=cicloViernesJueves();
  const hoy=iso(new Date());
  const ini=fechaValida(params.inicio)?params.inicio!:vigenteRango[0];
  const fin=fechaValida(params.fin)&&params.fin!>=ini?params.fin!:vigenteRango[1];
  const tab:Tab=tabs.some(([key])=>key===params.tab)?params.tab as Tab:'minuta';
  const [reg,res,min,vigente,platos,solicitudes,reclamos,responsables,satisfaccion,encuestas,reclamosHoy]=await Promise.all([getReglas(),resumenAdmin(),minutasPeriodo(ini,fin),minutasPeriodo(vigenteRango[0],vigenteRango[1]),platosDisponibles(),listarSolicitudesExtraordinarias('PENDIENTE'),listarReclamosParaRol('AdminCasino'),listarResponsablesReclamos(),resumenSatisfaccion(),listarEncuestasRecientes(),resumenReclamosJornada(hoy)]);
  const minOperativas=min.filter((row:any)=>String(row.fecha)>=hoy);
  const fechasOperativas=[...new Set(minOperativas.map((row:any)=>String(row.fecha)))];
  const proximaFecha=fechasOperativas[0]||'Sin minuta futura';
  const serviciosProxima=proximaFecha==='Sin minuta futura'?0:new Set(minOperativas.filter((row:any)=>String(row.fecha)===proximaFecha).map((row:any)=>String(row.servicio))).size;
  const nombresServicios=proximaFecha==='Sin minuta futura'?[]:[...new Set(minOperativas.filter((row:any)=>String(row.fecha)===proximaFecha).map((row:any)=>String(row.servicio)))];
  const href=(key:Tab)=>`/admin-casino?tab=${key}&inicio=${ini}&fin=${fin}`;

  return <AppShell user={u}><div className="space-y-5">
    <section><p className="text-xs font-extrabold tracking-[.18em] text-[#1DB954]">ADMIN CASINO</p><h1 className="text-2xl font-black text-[#0E2A23]">Operación y minutas</h1><p className="mt-1 text-sm text-[#6B7570]">Minuta oficial, excepciones y reglas operativas desde una sola fuente.</p></section>

    <section className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-extrabold tracking-[.14em] text-[#1DB954]">MINUTA OFICIAL VIGENTE</p><h2 className="text-xl font-black">Ciclo viernes → jueves</h2><p className="text-sm text-[#6B7570]">{vigenteRango[0]} → {vigenteRango[1]} · fuente única para Cocina, Comensal y perfiles autorizados.</p></div><Link href={href('minuta')} className="rounded-xl bg-[#0E2A23] px-4 py-2 text-sm font-black text-white">Gestionar próxima minuta</Link></div><MinutaPublicada rows={vigente.filter((row:any)=>String(row.fecha)>=hoy) as any} compactWeekly/></section>

    <section className="grid gap-3 md:grid-cols-4">{[['Reservas futuras',res.reservas],['Raciones futuras',res.raciones],['Pagos pendientes',res.pendientes],['Excepciones pendientes',solicitudes.length]].map(([a,b])=><div key={String(a)} className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-4"><div className="text-sm text-[#6B7570]">{a}</div><div className="text-3xl font-black text-[#0E2A23]">{String(b||0)}</div></div>)}</section>

    <nav className="flex flex-wrap gap-2 rounded-2xl border border-[#A6B0AA]/25 bg-white p-2">{tabs.map(([key,label])=><Link key={key} href={href(key)} className={`rounded-xl px-4 py-2 text-sm font-black ${tab===key?'bg-[#0E2A23] text-white':'text-[#0E2A23] hover:bg-[#F6F3EA]'}`}>{label}</Link>)}</nav>

    {tab==='jornada'&&<section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Inicio y cierre de jornada</h2><p className="mt-1 text-sm text-[#6B7570]">Admin Casino y Cocina trabajan sobre la misma jornada: raciones reservadas, producción, entregas, pagos, observaciones e incidencias. Los reclamos se resumen como contexto y nunca bloquean el cierre.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-[#F6F3EA] p-4"><b>Raciones futuras</b><div className="text-2xl font-black">{res.raciones||0}</div></div><div className="rounded-xl bg-[#F6F3EA] p-4"><b>Pagos pendientes</b><div className="text-2xl font-black">{res.pendientes||0}</div></div><div className="rounded-xl bg-[#F6F3EA] p-4"><b>Reclamos de hoy</b><div className="text-sm">{reclamosHoy.map((r:any)=>`${r.estado}: ${r.cantidad}`).join(' · ')||'Sin reclamos asociados'}</div></div></div><Link href={`/cocina?fecha=${hoy}`} className="mt-4 inline-block rounded-xl bg-[#1DB954] px-5 py-3 font-black">Abrir control operativo de hoy</Link></section>}

    {tab==='reclamos'&&<section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Gestión de reclamos</h2><p className="text-sm text-[#6B7570]">Expediente único, derivación y seguimiento por rol.</p><ReclamosGestion rows={reclamos}/><h3 className="mt-6 text-lg font-black">Responsables y correos por categoría</h3><div className="mt-3 grid gap-3 lg:grid-cols-2">{['Comida','Atención','Higiene','Infraestructura','Pago / deuda','Otro'].map(c=>{const actual=responsables.find(r=>r.categoria===c);return <form action={responsableReclamoAction} key={c} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-[140px_1fr_1fr_auto]"><input type="hidden" name="categoria" value={c}/><b className="self-center">{c}</b><input name="responsable" required defaultValue={actual?.responsable||''} placeholder="Responsable" className="rounded-lg border p-2"/><input name="correo" type="email" required defaultValue={actual?.correo||''} placeholder="correo@dominio.cl" className="rounded-lg border p-2"/><button className="rounded-lg border px-3 py-2 font-bold">Guardar</button></form>})}</div></section>}

    {tab==='satisfaccion'&&<section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Satisfacción post-servicio</h2><div className="mt-4 grid gap-3 md:grid-cols-4">{[['Respuestas',satisfaccion.respuestas],['Servicio promedio',satisfaccion.servicio||'—'],['Plataforma promedio',satisfaccion.plataforma||'—'],['Evaluaciones bajas',satisfaccion.bajas]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-[#F6F3EA] p-4"><div className="text-sm">{l}</div><div className="text-2xl font-black">{String(v)}</div></div>)}</div><div className="mt-4 space-y-2">{encuestas.slice(0,20).map((e:any)=><div key={e.id} className="rounded-xl border p-3 text-sm"><b>{e.fecha_servicio} · {e.codigo_reserva}</b> · Servicio {e.servicio_general}/5 · Plataforma {Number((e.plataforma_facilidad+e.plataforma_claridad+e.plataforma_agilidad)/3).toFixed(1)}/5{e.observacion_servicio&&<p className="mt-1">{e.observacion_servicio}</p>}</div>)}</div></section>}

    {tab==='solicitudes'&&<section className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">Solicitudes y excepciones pendientes</h2><p className="text-sm text-[#6B7570]">Solo casos que requieren una decisión de Admin Casino. Reclamos y futuras derivaciones podrán llegar a esta misma bandeja.</p></div><span className="rounded-full bg-[#D4AF37]/20 px-3 py-1 text-sm font-black">{solicitudes.length} pendiente(s)</span></div><div className="mt-4 space-y-3">{solicitudes.map((s:any)=><article key={s.id} className="rounded-xl border p-4"><div className="grid gap-2 md:grid-cols-[1fr_150px_150px]"><div><p className="text-xs font-bold uppercase tracking-wider text-[#6B7570]">#{s.id} · {s.tipo==='NO_CONSUMIRA_DIA'?'No consumirá el día':'Anulación de servicio'}</p><h3 className="text-lg font-black">{s.nombre||s.rut}</h3><p className="text-sm">RUT {s.rut} · Reserva {s.referencia_reserva||'—'}</p></div><div className="text-sm"><b>Fecha</b><br/>{String(s.fecha).slice(0,10)}</div><div className="text-sm"><b>Jornada</b><br/><span className={s.estado_jornada==='EN_PRODUCCION'?'font-black text-red-700':'font-bold'}>{s.estado_jornada}</span></div></div>{s.tipo==='ANULACION_SERVICIO'&&<div className="mt-3 rounded-lg bg-[#F6F3EA] p-3 text-sm"><b>{s.servicio}</b> · {s.plato}</div>}<div className="mt-3 rounded-lg bg-[#F6F3EA] p-3 text-sm"><b>Motivo:</b> {s.motivo}</div><form action={resolverSolicitudExtraordinariaAction} className="mt-3 grid gap-2 md:grid-cols-[1fr_auto_auto]"><input type="hidden" name="id" value={s.id}/><input name="observacion" placeholder="Observación de Admin Casino (opcional)" className="rounded-lg border px-3 py-2"/><button name="decision" value="RECHAZAR" className="rounded-lg border px-4 py-2 font-bold">Rechazar</button><button name="decision" value="AUTORIZAR" className="rounded-lg bg-[#1DB954] px-4 py-2 font-black">Autorizar</button></form></article>)}{!solicitudes.length&&<p className="rounded-xl bg-[#F6F3EA] p-4 text-sm">No existen solicitudes o excepciones pendientes.</p>}</div></section>}

    {tab==='minuta'&&<section className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">Gestión operativa de minutas</h2><p className="text-sm text-[#6B7570]">Solo se muestran hoy y fechas futuras. Los días vencidos quedan disponibles exclusivamente en Histórico y ya no pueden corregirse desde esta bandeja.</p></div><form className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="tab" value="minuta"/><label className="text-sm font-bold">Desde<input type="date" name="inicio" min={hoy} defaultValue={ini<hoy?hoy:ini} className="mt-1 block rounded-lg border p-2"/></label><label className="text-sm font-bold">Hasta<input type="date" name="fin" min={hoy} defaultValue={fin<hoy?hoy:fin} className="mt-1 block rounded-lg border p-2"/></label><button className="self-end rounded-lg border px-4 py-2 font-bold">Consultar</button></form></div>
      <div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-[#F6F3EA] p-4"><div className="text-xs font-bold uppercase tracking-wider text-[#6B7570]">Hoy</div><div className="mt-1 text-xl font-black text-[#0E2A23]">{hoy}</div></div><div className="rounded-xl bg-[#F6F3EA] p-4"><div className="text-xs font-bold uppercase tracking-wider text-[#6B7570]">Próxima fecha operativa</div><div className="mt-1 text-xl font-black text-[#0E2A23]">{proximaFecha}</div></div><div className="rounded-xl bg-[#F6F3EA] p-4"><div className="text-xs font-bold uppercase tracking-wider text-[#6B7570]">Servicios programados</div><div className="mt-1 text-xl font-black text-[#0E2A23]">{nombresServicios.join(' + ')||'Sin servicios'}</div><div className="text-xs text-[#6B7570]">{serviciosProxima} servicio(s)</div></div></div>
      <div className="mt-3 rounded-xl bg-[#EEF7F6] p-3 text-sm"><b>Ventana operativa:</b> {minOperativas.length?`${fechasOperativas[0]} → ${fechasOperativas[fechasOperativas.length-1]} · ${fechasOperativas.length} día(s) · ${minOperativas.length} fila(s)`:'No hay minutas futuras dentro del período consultado.'}</div>
      <MinutaCarga platos={platos}/><div className="mt-5 space-y-4">{fechasOperativas.map(fecha=><div key={fecha} className="rounded-xl border p-3"><h3 className="font-black">{fecha}</h3><div className="mt-2 overflow-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="text-left"><th>Servicio</th><th>Opción</th><th>Plato</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{minOperativas.filter((row:any)=>String(row.fecha)===fecha).map((row:any)=><tr key={row.id} className="border-t"><td>{row.servicio}</td><td>{row.tipo_opcion}</td><td>{row.plato}</td><td><b>{row.estado}</b></td><td><details><summary className="cursor-pointer underline">Corregir</summary><form action={minutaAction} className="mt-2 grid gap-2 md:grid-cols-4"><input type="hidden" name="id" value={row.id}/><input type="hidden" name="fecha" value={row.fecha}/><select name="servicio" defaultValue={row.servicio} className="rounded border p-1"><option>Desayuno</option><option>Almuerzo</option><option>Once</option><option>Cena</option></select><select name="tipo_opcion" defaultValue={row.tipo_opcion} className="rounded border p-1"><option>OPCION 1</option><option>OPCION 2</option><option>HIPOCALORICO</option><option>TIPO R</option></select><input name="plato" list="platos-minuta" defaultValue={row.plato} required className="rounded border p-1"/><button className="rounded border px-2 font-bold">Guardar corrección</button></form></details></td></tr>)}</tbody></table></div></div>)}{!minOperativas.length&&<p className="rounded-xl bg-[#F6F3EA] p-4 text-sm">No existen minutas operativas futuras en este período. Para revisar días anteriores usa la pestaña Histórico.</p>}</div></section>}

    {tab==='historico'&&<section className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">Histórico de minutas</h2><p className="text-sm text-[#6B7570]">Consulta de períodos anteriores en modo lectura. No forma parte de la bandeja operativa diaria y no permite correcciones.</p></div><form className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="tab" value="historico"/><label className="text-sm font-bold">Desde<input type="date" name="inicio" defaultValue={ini} className="mt-1 block rounded-lg border p-2"/></label><label className="text-sm font-bold">Hasta<input type="date" name="fin" defaultValue={fin} className="mt-1 block rounded-lg border p-2"/></label><button className="self-end rounded-lg border px-4 py-2 font-bold">Consultar histórico</button></form></div><MinutaPublicada rows={min as any} compactWeekly/></section>}

    {tab==='reglas'&&<section className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-5"><h2 className="text-xl font-black">Reglas de reserva</h2><p className="mt-1 text-sm text-[#6B7570]">Parámetros operativos autorizados. Tarifas e instituciones se centralizarán posteriormente en Admin Total.</p><form action={reglasAction} className="mt-4 grid gap-3 md:grid-cols-4"><label className="text-sm font-bold">Anticipación (h)<input name="a" defaultValue={reg.anticipacion_reserva_horas} className="mt-1 w-full rounded-lg border p-2"/></label><label className="text-sm font-bold">Cancelación (h)<input name="c" defaultValue={reg.cancelacion_directa_horas} className="mt-1 w-full rounded-lg border p-2"/></label><label className="text-sm font-bold">Máx. días<input name="m" defaultValue={reg.max_dias_consecutivos} className="mt-1 w-full rounded-lg border p-2"/></label><label className="flex items-end gap-2 pb-2 text-sm font-bold"><input type="checkbox" name="e" defaultChecked={Number(reg.excepciones_habilitadas)===1}/> Excepciones</label><button className="rounded-xl bg-[#1DB954] px-4 py-2 font-extrabold md:col-span-4">Guardar reglas</button></form></section>}
  </div></AppShell>
}
