import AppShell from '@/components/AppShell';
import { requireUser } from '@/lib/auth/session';
import { flujoActual, getReglas, minutasProximas, resumenAdmin } from '@/lib/db/admin';
import { enviarAction, minutaAction, reglasAction } from './actions';
export const dynamic='force-dynamic';
function iso(d:Date){return d.toISOString().slice(0,10)}
function semana(){const d=new Date(); const mon=new Date(d); mon.setDate(d.getDate()-((d.getDay()+6)%7)); const sun=new Date(mon);sun.setDate(mon.getDate()+6);return [iso(mon),iso(sun)]}
export default async function Page(){
  const u=await requireUser(['AdminCasino','AdminTotal']); const [ini,fin]=semana();
  const [reg,res,min,flujo]=await Promise.all([getReglas(),resumenAdmin(),minutasProximas(),flujoActual(ini,fin)]);
  return <AppShell user={u}><div className="space-y-5">
    <section className="grid gap-3 md:grid-cols-3">{[['Reservas futuras',res.reservas],['Raciones futuras',res.raciones],['Pagos pendientes',res.pendientes]].map(([a,b])=><div key={String(a)} className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-5"><div className="text-sm text-[#6B7570]">{a}</div><div className="text-3xl font-black text-[#0E2A23]">{String(b||0)}</div></div>)}</section>
    <section className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-5"><h2 className="text-xl font-black">Reglas de reserva</h2><form action={reglasAction} className="mt-4 grid gap-3 md:grid-cols-4"><label className="text-sm font-bold">Anticipación (h)<input name="a" defaultValue={reg.anticipacion_reserva_horas} className="mt-1 w-full rounded-lg border p-2"/></label><label className="text-sm font-bold">Cancelación (h)<input name="c" defaultValue={reg.cancelacion_directa_horas} className="mt-1 w-full rounded-lg border p-2"/></label><label className="text-sm font-bold">Máx. días<input name="m" defaultValue={reg.max_dias_consecutivos} className="mt-1 w-full rounded-lg border p-2"/></label><label className="flex items-end gap-2 pb-2 text-sm font-bold"><input type="checkbox" name="e" defaultChecked={Number(reg.excepciones_habilitadas)===1}/> Excepciones</label><button className="rounded-xl bg-[#1DB954] px-4 py-2 font-extrabold md:col-span-4">Guardar reglas</button></form></section>
    <section className="rounded-2xl border border-[#A6B0AA]/25 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Minutas</h2><p className="text-sm text-[#6B7570]">Editar la minuta invalida una autorización previa que cubra esa fecha.</p></div><form action={enviarAction} className="flex items-center gap-2"><input type="hidden" name="inicio" value={ini}/><input type="hidden" name="fin" value={fin}/><span className="text-sm">{ini} → {fin}</span><button className="rounded-lg bg-[#1DB954] px-3 py-2 font-bold">Enviar a Coordinación</button></form></div>{flujo&&<div className="mt-3 rounded-xl bg-[#F6F3EA] p-3 text-sm"><b>Flujo actual:</b> v{flujo.version} · {flujo.estado} · {flujo.observacion||'Sin observación'}</div>}
      <form action={minutaAction} className="mt-4 grid gap-2 rounded-xl border p-3 md:grid-cols-5"><input type="date" name="fecha" required className="rounded-lg border p-2"/><select name="servicio" className="rounded-lg border p-2"><option>Desayuno</option><option>Almuerzo</option><option>Once</option><option>Cena</option></select><select name="tipo_opcion" className="rounded-lg border p-2"><option>OPCION 1</option><option>OPCION 2</option><option>HIPOCALORICO</option><option>TIPO R</option></select><input name="plato" required placeholder="Plato" className="rounded-lg border p-2"/><button className="rounded-lg border border-[#1DB954] font-bold">Agregar minuta</button></form>
      <div className="mt-3 max-h-[520px] overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th>Fecha</th><th>Servicio</th><th>Opción</th><th>Plato</th><th>Estado</th></tr></thead><tbody>{min.map((r:any)=><tr key={r.id} className="border-t"><td className="py-2">{r.fecha}</td><td>{r.servicio}</td><td>{r.tipo_opcion}</td><td>{r.plato}</td><td>{r.estado}</td></tr>)}</tbody></table></div>
    </section>
  </div></AppShell>
}
